### ISSUE TITLE
Tilføj typeannotering til fire.cli.mtl

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#123]
`fire.cli.mtl` er delvist typeannoteret - den trænger til en overhaling, så alt er annoteret

**Comment by kbevers** [comment]
Jeg lukker lige den her på dine vegne, @TanyaPS.

Et tip til fremtiden: Hvis du i pull request eller commits skriver "Closes #123", så lukkes det pågældende issue automatisk når koden merges.
