### ISSUE TITLE
Længdespecifik empirisk varians, eller observationsvariansestimat?

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#158]
Tidligere diskussion ovre i #151: @kbevers oplyste om håndtering af varians på nivellementsobservationer at

> Den relevante del af migreringskoden må være her: https://github.com/Kortforsyningen/FIRE-DDL/blob/cb70f13f56c2c09b16ab6eced8fdf36d0622cdef/Migration/MakeObservation.sql#L90-L247 Jeg er dog ikke sikker på at det hjælper dig meget, det ser ret neutralt ud. Jeg kan godt grave dybere hvis ikke det er tilstrækkeligt, der gemmer sig muligvis noget i inbox et sted.

@busstoptaktik grublede videre og nåede frem til at:

> m.a.o. er det tal, der p.t. ligger i FIRE, en varians målt i m2. Jeg har så regnet den om til en spredning målt i mm. Og i materialet ovenfor checket efter at det passer sammen med det forventede, hvis man fjerner længdeskaleringen. Den korrekte søjlekommentar må så være:

> `Apriorivarians [m^2]`

> (det ændrer dog ikke ved at jeg stadig mener at tallet fra REFGEO, opgivet i nivellementsenheder, er mere informativt)

Senere undersøgelser førte til konklusionen, at der i REFGEO befinder sig observationer med ukendt længde, registreret som 0 (og i øvrigt også med ukendt antal opstillinger registreret som 0), hvorved den afstandsafhængige varians ligeledes bliver 0. Vi kan regne os frem til en mindsteværdi ved at bruge den geodætiske afstand mellem de to implicerede punkter, når vi har den specifikke varians, men ikke omvendt, når den en gang er blevet ganget med nul.

**Comment by kbevers** [comment]
Fin opsummering af problemstilling, men hvad skal gøres for at dette issue kan lukkes? Ændring i datamodel+migrationskode?

**Comment by busstoptaktik** [comment]
> Ændring i datamodel+migrationskode?

I hvert fald i migrationskoden (som forenkles lidt). For datamodellens vedkommende er det kun en ændring i beskrivelsen af observationstypen. Jeg kigger lige sidst på dagen...

**Comment by kbevers** [comment]
Fikset i https://github.com/Kortforsyningen/FIRE-DDL/pull/171
