### ISSUE TITLE
Installationsvejledning skal inkludere Oracle instantclient

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#161]
Conda installerer tilsyneladende ikke Oracle instantclient, så installationsvejledningen skal udvides med et afsnit om hvordan det gøres. Meget kort:

1. download fra https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html
2. pak ud i `C:\oracle\`
3. Tilføj `C:\oracle\instant_client_x_y` til `%PATH%`

Der bør nok inkluderes et billede eller to der viser hvordan man indsætter nye variable i PATH.

**Comment by busstoptaktik** [comment]
> Der bør nok inkluderes et billede eller to der viser hvordan man indsætter nye variable i PATH.

Det kan man tilsyneladende ikke, hvis man ikke har SITs special blessing. Jeg kan i hvert fald ikke, så jeg bruger en separat opsætnings-.cmd-fil

**Comment by kbevers** [comment]
Vi har lige så lige gjort det på Tanyas PC uden problemer. Miljøvariabelvinduet er blevet ændret i en opdatering siden jeg sidst har brugt den. Det fungerer faktisk ret fornuftigt nu. Prøv selv skriv "miljøvariabel" i startmenuens søgefelt

**Comment by busstoptaktik** [comment]
> Prøv selv skriv "miljøvariabel" i startmenuens søgefelt

Yes - den giver en reference til et hjørne af kontrolpanel, som jeg så ikke kan få lov til at åbne: Jeg kan klikke på den, men der sker intet - SIT roolz here :-)

**Comment by busstoptaktik** [comment]
... håhåhååååå - tredje gang jeg klikkede åbnede dialogen sørme. I will kick on it :-)

**Comment by kbevers** [comment]
Sådan :-)

**Comment by kbevers** [comment]
Og her er noget grafik der kan indsættes i dokumentationen

![image](https://user-images.githubusercontent.com/13132571/82899301-08ff2280-9f5b-11ea-92c5-b06fc735a836.png)

![image](https://user-images.githubusercontent.com/13132571/82899353-1d431f80-9f5b-11ea-9aea-14820db8c083.png)

**Comment by busstoptaktik** [comment]
Ny statistik: Fungerer ca. 4 ud af 10 gange, men man skal tilsyneladende helt ud af startmenuen mellem hvert forsøg (om end jeg ikke gider forsøge at opbygge yderligere evidens for om det måske bare var et tilfælde)

**Comment by kbevers** [comment]
Den rigtige måde at beskrive det på er nok hvordan man finder frem til den rigtige dialogboks via kontrolpanelet.

**Comment by busstoptaktik** [comment]
> Den rigtige måde at beskrive det på er nok hvordan man finder frem til den rigtige dialogboks via kontrolpanelet.

Den vej kan jeg desværre ikke komme til tingene. Det er som om der er et trin i stien fra kontrolpanelets top og ned til det ny miljøvariabelredigeringsprogram, som er blokeret af SIT, eller gjort usynligt eller noget.

Jeg kan komme til HKEY_CURRENT_USER\Environment\Path via regedit, men ikke via kontrolpanel. Jeg tror jeg må give op på denne: Det er ikke hensigtsmæssigt at sidde og skrive en vejledning på en PC, der tydeligvis er lidt ude af takt med det rimelige.
