### ISSUE TITLE
Sprogkorrektioner hele vejen fra DDL og op til overfladen

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#169]
Som nævnt ovre på #164: ... men også en reminder om måske lige at få rettet stavefejl (Eventype, fx) og -inkonsekvenser (...punktid vs. ...punktsid) etc. i DDLen, før vi går live. Desværre kræver det jo en ekstra migrering og nok også konsekvensrettelser hos @Helle-Git, men næppe værre end at de kan overkommes, især hvis @Helle-Git bliver reviewer på det implementerende PR

**Comment by kbevers** [comment]
Det er nok en fordel hvis vi i første omgang laver en liste med de ændringer der skal laves, ellers er det lidt for ukonkret.

Her er en start:

- "Eventype" - forekommer pt to steder i `sql\ddl.sql`. Enten som tabelindhold eller kommentar. Ingen konsekvenser ved ændring
- "observationtype" - Det falder mere naturligt at skrive "observation*s*type", hvilket også bruges i fx "observationstypeid" i observationstabellen. Migrerings-, API-, og mappingkode skal tilpasses hvis det ændres. Både tabelnavn og kolonnenavne skal ændres.

**Comment by busstoptaktik** [comment]
* id bruges som attribut på `Punkt` og `Observation`, men er også en builtin-funktion. Erstat evt med `uuid` eller noget andet og bedre?
