### ISSUE TITLE
Gør fire info infotype mere brugervenlig

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#176]
- Vis liste når `fire info infotype` kaldes uden argument
- Søg case-insensitive så `fire info infotype NET:10km` og `fire info infotype NET:10KM` begge giver et brugbart resultat

**Comment by busstoptaktik** [comment]
Vile også være nyttigt med partiel søgning: `fire info infotype ATTR`, eller `fire info infotype NET`  fx

**Comment by kbevers** [comment]
Ja, det vil være brugbart. Noget lignende kan også indføres i `fire info srid`.
