### ISSUE TITLE
Observationer bør have UUID - eller også ej...

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#182]
Ovre i [FIRE-DDL](https://github.com/Kortforsyningen/FIRE-DDL/blob/6674d564b4f603e6e06f78df40303015b86a6cce/Migration/MakeObservation.sql#L8-L22) kan man se at `Observation.gruppe` for nivellementsobservationer simpelthen er journalsidenummeret, uden undernummer.

Jeg *tror* at det var meningen at undernummeret (fx ettallet i 207302.1) skulle ned i `Observation.antal`, som i så fald snarere burde have heddet `index`. I hvert fald er det fulde journalsidenummer unikt for nivellementsobservationer, og kunne være brugt som (U)UID, hvis vi havde sørget for at få undernummeret med i kassen. Det sker tilsyneladende ikke under migreringen (alle nivellementsundernumre ser - for en stikprøvebetragtning - ud til at være sat til 1).

Det betyder at den unikke identifikation der benyttes i APIet til at identificere observationer med simpelthen er objektid (recordid, som på dansk strengt taget må hedde postnummer... men det betyder jo noget andet).

Det giver lidt høne-og-ægproblemer, fordi man først kan referere entydigt til en observation når den **er** lagt i databasen, men på den anden side ikke har nogen simpel mulighed for stensikkert at få eksakt den klat observationer retur man lige har lagt i: De er registreret på `sagseventfra`, men også den kender man først når klokken har slået.

Så vi *kunne* få en entydig identifikation ved at bruge journalside + underside i `gruppe`og underside i `antal`, men der er jo en vis risiko for at journalsider er entydige via håndholdte aftaler, ikke via robuste systemer. Så alt i alt er jeg ved at være i stemning for at gøre begge dele (så længe vi HAR journalsider): Tildele dem UUIDer der hvor de genereres (enten i migrations, eller i produktionssystemet, afhængigt af om det er gamle eller nye data) **og** proppe undersiden i *antal* og måske omdøbe til index: Det ene sted i APIet jeg kan finde *antal* i brug er jeg ret sikker på at det er brugt forkert ([her](https://github.com/Kortforsyningen/FIRE/blob/a7190587ed043ca232e78ef655440ad95f686dc9/fire/api/gama/networkdoc.py#L155-L180)), så det ser ud til at være minimalt risikabelt at udnytte.

**Comment by kbevers** [comment]
> Jeg tror at det var meningen at undernummeret (fx ettallet i 207302.1) skulle ned i Observation.antal, som i så fald snarere burde have heddet index

Det er vist ikke helt rigtigt. Vi skriver sådan her som kommentar til feltet `antal`:

```
COMMENT ON COLUMN OBSERVATION.ANTAL IS 'Antal gentagne observationer hvoraf en middelobservationen er fremkommet.';
```

Jeg synes ikke det matcher det du beskriver med undernummer, som jeg forstår som "observation nummer *n* på journalside *xyz*". 

I https://github.com/Kortforsyningen/FIRE-DDL/blob/master/Migration/MakeObservation.sql kan man se at for geometrisk nivellement kommer `antal` fra `ni_niv.sets` i REFGEO, hvorom der i kommentarerne på tabellen står:

> Number of single measurements in this set-up (used as weight in computation)


> Det ene sted i APIet jeg kan finde antal i brug er jeg ret sikker på at det er brugt forkert (her), så det ser ud til at være minimalt risikabelt at udnytte.

Ud fra ovenstående vil jeg mene at `antal` bruges korrekt. Det ligner ganske meget at det bruges til at vægte en usikkerhed med.

**Comment by busstoptaktik** [comment]
> Ud fra ovenstående vil jeg mene at antal bruges korrekt. Det ligner ganske meget at det bruges til at vægte en usikkerhed med.

Yes - den er god nok: Det er variansen der vægtes, ikke spredningen, og dermed bliver det korrekt at kombinere lineært, og dividere med n istf sqrt(n). Fordi vi - i denne version af migreringen - har omregnet fra REFGEOs længdespecifikke til observationsspecifik varians.

Jeg skal bare lige have checket op på at den længdeuafhængige del bliver håndteret korrekt også (altså under migreringen bliver ganget med antallet af opstillinger).

I dag vil man jo bare kaste alle observationer ind i udjævningen og dermed få korrekt vægtning og samtidig aposteriori kvalitetsvurdering af både frem- og tilbagemålingen. Men i ældre tider var det en fordel at reducere ligningssystemets størrelse ved at summere frem- og tilbagemåling. Jeg kan se at det er sket i 1. præs-målingerne til GM902, 1892 og 1894 - men *ikke* ved 2. præs 1946

Så den er principielt fin nok, hvis den afstandsuafhængige del også er det. Men er det ikke efter næste remigrering, hvor vi vender tilbage til længdespecifikke variansmål.

Men så meget desto mere: Der er brug for en UUID for observationer - eller det vil i hvert fald væsentligt forenkle håndteringen af dem.

**Comment by busstoptaktik** [comment]
> Der er brug for en UUID for observationer

(og med UUID mener jeg så enten en reel UUID, eller, lettere, en sammensat nøgle bestående af endepunkts-id'erne i kombination med observationstidspunktet).

**Comment by busstoptaktik** [comment]
Jeg sad tidligere og sammenlignede [dette fra FIRE-DDL](https://github.com/Kortforsyningen/FIRE-DDL/blob/6674d564b4f603e6e06f78df40303015b86a6cce/Migration/MakeObservation.sql#L119-L120) med [dette fra FIRE API](https://github.com/Kortforsyningen/FIRE/blob/a7190587ed043ca232e78ef655440ad95f686dc9/fire/api/gama/networkdoc.py#L162-L164) og kunne ved grød ikke få ind i grøden hvordan det kunne passe sammen.

Det kunne det heller ikke, for de to første linjer er fra den version af FIRE-DDL jeg selv har opdateret for en uges tid siden, mhp forberedelse til #163 - som jo altså ikke er merget endnu, og som, kan jeg nu se, skal udvides med en korrektion af FIRE GAMA-APIet

**Comment by kbevers** [comment]
> Men så meget desto mere: Der er brug for en UUID for observationer - eller det vil i hvert fald væsentligt forenkle håndteringen af dem.

Jeg foretrækker at vi bruger UUID'er. De er nemme at generere i migrationen og gør det også nemt at skabe standardisere id'er før observationerne rammer databasen. Det kræver så en form for oversættelse fra journalside+observationsnummer til UUID. Jeg gætter på at det relativt let kan gøres i forbindelse med oversættelse af rådatafiler til observationsregneark. Spørgsmålet er så bare om det er nødvendigt at holde styr på en liste der mapper journalside+obsnummer til UUID'er? Det er i hvert fald aktuelt hvis vi vil dumpe rådatafilen i databasen, da man ellers får svært ved at finde ud af hvilke observationer i rådatafilen der passer til observationer i databasen. Om det er nødvendigt at kunne er jeg ikke sikker på.

> Det kunne det heller ikke, for de to første linjer er fra den version af FIRE-DDL jeg selv har opdateret for en uges tid siden, mhp forberedelse til #163 - som jo altså ikke er merget endnu, og som, kan jeg nu se, skal udvides med en korrektion af FIRE GAMA-APIet

Det er også ved at være svært at holde tungen tilpas lige i munden på det her område! Og ja, gama koden skal tilpasses. Nu ved vi så endda også hvor :-)

**Comment by busstoptaktik** [comment]
> Det kræver så en form for oversættelse fra journalside+observationsnummer til UUID

Jeg synes bare vi skal ignorere problemet og behandle journalsidenummeret *næsten* som vi behandler REFGEO-id: Gammelt lort, der for REFGEO-ids vedkommende ikke behøver videremigreres næste gang vi skifter databasestruktur. Men som for journalsidernes vedkommende trods alt giver os den gruppering, som er nyttig til at skabe overblik i observationslisten - og som alligevel skal være en del af observationsdatatypen, fordi grupperingen er essentiel mht. vinkelmålinger, hvor der kan være mange observationer fra samme opstilling.

UUIDerne er fantastisk lækre fordi de kan genereres ud af den blå luft, når man importerer rådatafilerne. **Men** det vil så ske hver gang man laver en prøveimport, og derfor skal vi alligevel ned og checke mht. opstillingspunkt, sigtepunkt, og observationstidspunkt (hvis vi først laver dem når vi lægger tingene i databasen så er vi tilbage ved hønen og ægget-problemet: De er ikke tilgængelige når vi senere skal konstruere et beregningsobjekt, der kan trilles i databasen).

Vi kan komme uden om det ved at konstruere en UUID der principielt er tilfældig, men hvor tilfældigheden (i nivellementstilfældet) er deterministisk afledt af  journalside, observationstidspunkt, og de to punkter.  Det kan godt lade sig gøre - jeg vil gerne bruge et par timer på en prøveklud: Det er alligevel i min kode den skal leve. Og det er ikke imod nogen principper for god UUID-opførsel.

For de dele der allerede ligger i databasen skal der naturligvis bare trækkes en helt almindelig UUID ud af den blå luft.

**Comment by kbevers** [comment]
> UUIDerne er fantastisk lækre fordi de kan genereres ud af den blå luft, når man importerer rådatafilerne. Men det vil så ske hver gang man laver en prøveimport,

Jeg forstår ikke hvad et "prøveimport" er. Det er nok fordi jeg ikke forstår det workflow du arbejder på. Det forekommer mig at problemet ikke er stort hvis der arbejdes med en rådatafil-oversætter, der konverterer rådatafilerne til det regnearksbaserede format een gang for alle. Altså sådan at oversættelsen kun sker en gang, og resten af arbejdet foregår i regneark hvor der kan laves alle de iterationer man har lyst til hvor UUID'er naturligvis beholdes på tværs af iterationer. Det er dog stadig uklart for mig om det er sådan du vil gribe det an eller ej.

**Comment by busstoptaktik** [comment]
> Altså sådan at oversættelsen kun sker en gang

... og virkeligheden er desværre så bare at det nok er utænkeligt. Blandt andet fordi de samme data checkes igen og igen efterhånden som der måles mere op. Verden er grim og usystematisk. Regnvejr, busser og hundeslæder der kommer på tværs, stress på landevejen oversete detaljer af alle slags, radiolinks der går ned, og tilfældige bløp i bitstrømmen. Det er nødvendigt med offlinerobuste arbejdsgange.

**Comment by kbevers** [comment]
Jeg forsøger at lave en løsning på den her problemstilling, i hvert fald hvad angår DDL og API. Det burde også være til at håndtere i migrationen men det samler jeg lige til bunke sammen med en med masse andre ændringer.
