### ISSUE TITLE
G.M.-identer undervurderes

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#198]
Sorteringsfølgen for identer, indført ovre i #190 tager ikke hensyn til at nogle G.M.-identer er registrerede som `IDENT:diverse`, ikke `IDENT:GI`. Dette gælder bl.a. fundamentalpunktet GM902. Det betyder at disse punkter refereres til som landsnummer, istf. det mere fortællende GM-nummer.

Jeg ved ikke om uhensigtsmæssigheden skal rettes i migreringen, eller i `@property Punkt.ident()`

**Comment by kbevers** [comment]
Det bør håndteres i migrering. Giv mig en håndfuld eksempler på identer der fejlklassificeres, så ser jeg på det når jeg er tilbage på kontoret.

**Comment by busstoptaktik** [comment]
Jeg har ikke VPN-adgang de næste par uger, så jeg kan kun referere til GM902, Århus Domkirke, som eksempel på at det går galt: Den får sit landsnummer som hovedreference. Så vidt jeg husker er GM901, Domkirkepladsen, OK - men jeg er ikke sikker.

**Comment by majbrittws** [comment]
Liste over punkter, som fremgår med landsnummer:
gm110
gm901
gm902
gm903
gm904
gm1166.1
gm684
....
Jeg er ikke stødt på nogle G.I.-numre, som vises forkert, det er vist kun G.M.'erne (nogle af dem)
Eksempler på G.M.-numre, som dog vises korrekt: gm1082, gm1094, gm1207 ...

**Comment by kbevers** [comment]
Fikset i https://github.com/Kortforsyningen/FIRE-DDL/pull/175
