### ISSUE TITLE
Opdel test-suite i unit- og integrationstest

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#207]
### Problem

I øjeblikket er stort set alle tests afhængige af at kunne forbinde til en database hvor testdatasættet er indlæst. Dette er en hæmsko i udviklingen, da vi ikke har nem adgang til en test-database på arbejdsstationerne. 

### Definitioner

Unittests: Tests der verificerer logikken i en funktion uden at interagere med andre systemer (fx en database)

Integrationstests: Tests der verificerer at en funktion virker som den skal når den interagerer med andre systemer (fx databasen)

### Løsning

Ved hjælp af [mocking](https://en.wikipedia.org/wiki/Mock_object) af API-kald der trækker information ud af databasen kan vi lave en række tests der kan afvikles (hurtigt) lokalt. Det burde forbedre udviklingsarbejdsgangene markant. Det er dog ikke en lille opgave at stable en række unittests på benene.

I praksis kan testsuiten opdeles i to, sådan at filer under `test/` placeres i henholdsvis `test/unit` og `test/integration/`. Der vil skulle skrives en lang række unittests for at sikre en tilstrækkelig kodedækning for begge typer tests. 

Afvikling af unittests (uden integrationstests) kan gøres vha `pytest -k unit`.

**Comment by busstoptaktik** [comment]
@kbevers du er vist langt med denne allerede, men jeg lægger denne pind under projekt Post-MVP, så vi kan få den prioriteret af højere magter

**Comment by kbevers** [comment]
Langt og langt. Jeg har en branch et eller andet sted med de indledende knæbøjninger. Det kan jeg jo lige starte med at få lagt ind, mind mig gerne om det ved lejlighed :-)
