### ISSUE TITLE
Git-installation - afsnit i "Installationsvejledning"

### ISSUE THREAD

**Issue by majbrittws** [Kortforsyningen/FIRE#208]
Git skal også installeres for at man let kan opdatere sit repository. Beskrivelse for hvordan man gør det, skal tilføjes vejledningen.

**Comment by kbevers** [comment]
Git og (måske) Oracle Instantclient kan installeres via software center. Hvis det virker gør det alting meget simplere. Jeg er netop i gang med at teste det på en ren maskine.
