### ISSUE TITLE
Prevent attaching FikspunktregisterObjekter to an existing Sagsevent

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/FIRE#22]
A `Sagsevent` identifies `FikspunktregisterObjekt`er which was inserted in the same commit.

So, try to prevent using it wrong.

Could be by checking the session on `before_flush` like here https://docs.sqlalchemy.org/en/latest/_modules/examples/versioned_rows/versioned_rows.html

**Comment by busstoptaktik** [comment]
> A Sagsevent identifies FikspunktregisterObjekter which was inserted in the same commit.

While this is not part of the original design (since the data model does not relate to any actual implementation, and hence does not know about the "commit" concept), it does make ample sense to introduce this limitation (and its enforcement) as an implementation detail.

**Comment by busstoptaktik** [comment]
@AsgerPetersen: Whom should this be assigned to?

**Comment by AsgerPetersen** [comment]
@busstoptaktik I have assigned it to @bjornharrtell

**Comment by busstoptaktik** [comment]
Jf. #228 - @kbevers kan du se tvingende grunde til at dette skal være på plads inden vi går i luften med MVP? Hvis ikke skal vi have den kommende styregruppe til at tage ansvar for prioriteringen af dette element, ved at tilføje den til projekt Post-MVP (det er svar nok hvis du tilføjer pinden til projekt Post-MVP)

**Comment by kbevers** [comment]
Har i praksis ikke vist sig at udgøre et problem. Lukkes.
