### ISSUE TITLE
Should it be possible to distinguish between a closed and a deleted fikspunktregisterobjekt?

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/FIRE#228]
A `FikspunktregisterObjekt` is never deleted. Instead it's `registreringtil` is set to `sysdate`.

Should it be possible to distinguish between an object being unregistered because it is superseeded by a new "version" and because it is plain wrong?

I think it could make a difference when making time series where you (probably) do not want to include "wrong" objects.

**Comment by busstoptaktik** [comment]
@kbevers kan du se tvingende grunde til at dette skal være på plads inden vi går i luften med MVP? Hvis ikke skal vi have den kommende styregruppe til at tage ansvar for prioriteringen af dette element, ved at tilføje den til projekt Post-MVP (det er svar nok hvis du tilføjer pinden til projekt Post-MVP)

**Comment by kbevers** [comment]
Ja, den her bør vi få løst inden vi går i produktion. I hvert fald en modificeret version. Det er, som Asger også nævner, primært koordinattabellen der har et problem. Altså det med tidsserierne. Løsninger er ganske simpelt at tilføje en ekstra kolonne til koordinattabellen der afgør om den givne koordinat er slettet.

**Comment by busstoptaktik** [comment]
OK @kbevers - nu husker jeg at vi har snakket om det før... det betyder at der er tale om en separat proces ifht at sætte "registreringtil". Rent juridisk skal koordinaten jo stadig være tilgængelig, men vi skal selvfølgelig slukke for udstilling (eller reaktivere en tidligere værdi), hvis det er den aktuelle koordinatværdi, der skal slukkes for.

Men håndteringen må være en Post-MVP ting - for indeværende er det vel tilstrækkeligt at få søjlen ind i DDL, og få tænkt sagshændelsesstruktur for anvendelsen?

**Comment by kbevers** [comment]
> Men håndteringen må være en Post-MVP ting - for indeværende er det vel tilstrækkeligt at få søjlen ind i DDL, og få tænkt sagshændelsesstruktur for anvendelsen?

Ja, det meste kan klares på bagkant. Jeg vil gerne have DDL'en på plads inden vi går i produktion - den er træls at ændre på efterfølgende.

**Comment by busstoptaktik** [comment]
Så noget en ekstra linje a la

```SQL
FEJLMELDT INTEGER
```
ovre i https://github.com/Kortforsyningen/FIRE-DDL/blob/e07716a1512223aa53786303e5439c0fe1a13d1e/DDL.sql#L49-L67?

(eller NUMBER(1), som jeg har googlet mig til er den foretrukne erstatning for boolean i Oracles tilfælde)

**Comment by kbevers** [comment]
Ja. Og så en konsekvens tilpasning af Python API. Det er max en halv dags arbejde.
