### ISSUE TITLE
When and how to "Close" a FikspunktregisterObjekt

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/FIRE#23]
A `FikspunktregisterObject` is never deleted. Instead it is "closed" by setting `registreringtil` to `sysdate`.

Maybe make a convenience method for doing this
```python
FireDb.luk_objekt(objekt: FikspunktregisterObjekt)
```

We may also be able to identify situations where inserting new objects should trigger closing of existing objects. This should possibly happen automatically in the corresponding convenience methods.

**Comment by bjornharrtell** [comment]
This has come up specifically regarding Koordinat in https://github.com/Septima/fikspunktsregister/pull/63 comments.

**Comment by kbevers** [comment]
This should be accompanied with a SagsEvent that explains why the object was closed. There are different types of SagsEvent depending on what is being closed: `koordinat_nedlagt`, `observation_nedlagt`, `punktinfo_fjernet` and `punkt_fjernet`. There is a chance that this can't (or shouldn't) be handled by a generic `luk_objekt` function.

**Comment by AsgerPetersen** [comment]
...and it requires us to use a "delete record" to be able to add a sagsevent. Ie a record with identical registreringfra and registreringtil.

**Comment by kbevers** [comment]
That too, yes
