### ISSUE TITLE
Wildcard på søgefunktion ved danske fikspunkter

### ISSUE THREAD

**Issue by majbrittws** [Kortforsyningen/FIRE#238]
Når punkter søges frem via "fire info punkt", vil det være smart at kunne benytte et wildcard (igesom ved grønlandske og færørske punkter pt). 
Fx K-41-90%% eller gi21%%

Foranstillede nuller er måske bøvlet? (hvis de mangler, i hvert fald)..

**Comment by kbevers** [comment]
Brug `fire søg punkt` istedet for, fx 

``` 
fire søg punkt K-41-90%
`` `

Når du har fundet det punkt du leder efter kan du da proppe det ind i `fire info punkt`.

Bemærk: Der er en fejl i ´fire info søg` lige nu, en rettelse er på vej i #239.

**Comment by kbevers** [comment]
> Bemærk: Der er en fejl i ´fire info søg` lige nu, en rettelse er på vej i #239.

... og nu er den merget. Åben en terminal i dit fire repository og installer vha

```
conda activate fire
git checkout master
git pull
pip install -e .
```

**Comment by majbrittws** [comment]
Hmm, det løser ikke helt opgaven. Med 'fire søg punkt' får jeg kun en identliste frem. Jeg ville gerne have punktinfo på flere punkter af gangen.. Og når det virker sådan for de grønlandske numre, tænkte jeg det også burde virke sådan for de danske?

Derudover; Der er noget uoverensstemmelse i hvordan versaler og punktummer behandles i hhv 'fire info punkt' og 'fire søg punkt'. Det er lidt uhensigtsmæssigt, tænker jeg.
For 'fire info punkt' dur: GI2010, gi2010 og G.I.2010, men ikke g.i.2010.
For 'fire søg punkt' dur: G.I.2010 og g.i.2010, men ikke GI2010 og gi2010.
Ideelt set skal alle fire udgaver kunne du :)

**Comment by kbevers** [comment]
> Med 'fire søg punkt' får jeg kun en identliste frem

Pointen var jo så at du skal slå dem op med `fire info punkt` bagefter. Vi kan evt. udvide `fire info punkt` sådan at man kan give den mere end et ident hvis det er brugbart. Altså fx `fire info punkt SKEJ HABY`.

> Og når det virker sådan for de grønlandske numre, tænkte jeg det også burde virke sådan for de danske

At det fungerer sådan for punkter i Nordatlanten vil jeg betegne som en fejl. Kan du give et par eksempler på grønlandske punkter der gør som du nævner og tilsvarende eksempler fra Danmark som ikke gør det.

> For 'fire info punkt' dur: GI2010, gi2010 og G.I.2010, men ikke g.i.2010.
> For 'fire søg punkt' dur: G.I.2010 og g.i.2010, men ikke GI2010 og gi2010.

Det er et separat problem. Opret et nyt issue, så ser jeg på det.

**Comment by majbrittws** [comment]
> At det fungerer sådan for punkter i Nordatlanten vil jeg betegne som en fejl. Kan du give et par eksempler på grønlandske punkter der gør som du nævner og tilsvarende eksempler fra Danmark som ikke gør det.

Fx 'fire info punkt 567%'
De første 20 vises; resten kan man tilvælge at vise med -n parameteren.

Dog ser det ud til at det er underordnet om man skriver %567% eller 567%... Men ved %567, kommer kun punktnumre frem, som ender på 567. Men det er måske også et andet issue? 

Ingen af de danske dur, fx 123-01-%, G.I.20%, K-41-90%

**Comment by kbevers** [comment]
Det er en bivirkning af denne logik:

https://github.com/Kortforsyningen/FIRE/blob/37b6fa8f2e9a1b6c239ad142c314ffe962ab1461/fire/api/_firedb_hent.py#L80-L93

som bør opdateres så den er mere i tråd med hvad der sker for de danske identer. Kort sagt, så har vi brugt meget tid på at optimere koden til det danske tilfælde og nærmest ikke for det nordatlantiske.
