### ISSUE TITLE
Rationalisering af historikflag

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#247]
For `fire info punkt` har vi p.t. flagene `-K/--koord` og `-o/--obs` til at håndtere udvalg af hhv. koordinater og observationer. Desuden foreligger en patch (#246) som, uden tilhørende flag, markerer om en punktinformation er historisk ("slukket") eller gældende.

@kbevers foreslår i kommentarsporet til #246 at indføre et mere overordnet tilvalg `-H/--historik` der kan styre alle aspekter af historikvisningen. Jeg tilføjer for egen regning: Valg af historikvisning for koordinater, (observationer), geometrier, punktinformationer.

Dertil hører også naturligt valg af om der skal vises tidsstempler (fra/til, bare fra, eller slet ingen) for historiksporet. Det vil næppe være praktisk at læsse al denne funktionalitet over på et enkelt, stakkels `-H`-flag, men det vil givetvis være værdifuldt at opbygge en lille gruppe af flag, der kan forbedre og strukturere historikvisningen.

Det er imidlertid en grundidé, der skal have tid til at modne - så mit forslag er at være åbne for merging af yderligere historikfunktionalitet, og så, efterhånden som behov og use-cases bliver tydeligere, diskutere `-H` og hendes potentielle søskende herunder.

**Comment by busstoptaktik** [comment]
Ville det mon fungere hvis historik var en alt-eller-intet ting, så `-H` giver historik både for koordinater og attributter, `-K` vælger *hvilke* typer koordinater der skal uddkrives, `-O` *hvilke* typer observationer - og måske et `-L` til at inkludere lukkede observationer?

**Comment by kbevers** [comment]
Det tror jeg sagtens kan fungere. 

Hvis det ændres skal dokumentationen (især workshopdelen) konsekvensrettes. Der er en del skærmbilleder som kommer til at være forældede.

**Comment by busstoptaktik** [comment]
@kbevers skriver ovre på #442 om `fire info punkt` med historik:

> Nå ja. Den funktionalitet er jeg ikke sikker på er så nyttig som oprindeligt tiltænkt

Jeg har ikke skarp nok hukommelse til at forholde mig til hvad der oprindeligt var tiltænkt, men jeg bruger den funktionalitet noget nær dagligt for at kunne lave A/B-tests dels ved ilægning af nye data, dels på kryds og tværs af test/prod (fordi for længst udførte ændringer i test står tydeligt frem i forhold til prod).

Funktionaliteten ville være mere anvendelig hvis der var tale om et tilvalg (præcis som dette issue jo handler om) frem for standardhandlingen: Jeg har nok kun brug for `-H` cirka hver femte gang jeg taster `fire info punkt` (hvilket så i øvrigt nok sker ca. 25 gange om dagen)

**Comment by kbevers** [comment]
> Jeg har ikke skarp nok hukommelse til at forholde mig til hvad der oprindeligt var tiltænkt,

Det var vist meget specifikt noget med at kunne følge udviklingen i `ATTR:bemærkning` og evt. også `ATTR:beskrivelse`. Efter nu at have set det temmelig mange gange er jeg overbevist om at det ikke tilføjer speciel værdi i standardvisningen.

**Comment by busstoptaktik** [comment]
> Det var vist meget specifikt noget med at kunne følge udviklingen i ATTR:bemærkning og evt. også ATTR:beskrivelse. Efter nu at have set det temmelig mange gange er jeg overbevist om at det ikke tilføjer speciel værdi i standardvisningen.

Lige præcis de to attributter er temmeligt ligegyldige i de fleste af mine sammenhænge: De fylder ganske rigtigt usigeligt meget hver gang der er rettet et komma, mellemrum eller noget endnu mindre (og netop derfor væsentligt at historik er et tilvalg, frem for en standard). Men for provokerede opdateringer (og bare generel nysgerrighed) er det ret anvendeligt til bevarelse af overblikket. Jeg ville nødig undvære det.

**Comment by kbevers** [comment]
> Jeg ville nødig undvære det.

Jeg skal lige sikre at jeg forstår dig ret. Du vil nødig undvære historikvisningen som standard? Eller er det generelt hvis man slet ikke kan se historikken? Sidstnævnte havde jeg ingen intention om at ændre ved.

**Comment by busstoptaktik** [comment]
Nej, jeg vil helst have historikvisning som tilvalg, for det er kun cirka hver femte gang jeg skal bruge den, og formodentlig meget sjældnere for alle andre. Men det medfører at `punkt.punktinformationer` også skal indeholde de historiske informationer - det var der diskussionen startede.
