### ISSUE TITLE
Manglende constraint på PUNKTINFO tabellen

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#254]
Det er, ved en fejl, lykkedes mig at introducere tomme punktinfo `IDENT:GNSS` for to nyoprettede testpunkter GL 88888 og GL 88889.

Det kræver en del udenværker i `api/model/punkttyper.py` at arbejde uden om det, for ident-logikken er ikke forberedt på at få `None`-værdier smidt i hovedet, så hun går i gulvet med et drøn og tager både `fire info punkt` og `fire info søg` med sig.

For de næste par uger er det nok nødvendigt at have udenværkerne i koden (jeg kommer med et PR om lidt), men det ville være en pænere løsning at sikre at det relevante felt ikke er None/NULL for `PunktInfoTypeAnvendelse.TEKST` og `PunktInfoTypeAnvendelse.TAL` (og at de begge *er* None/NULL for `PunktInfoTypeAnvendelse.FLAG`)

**Comment by busstoptaktik** [comment]
@kbevers - glemte lige at namedroppe dig her...

**Comment by kbevers** [comment]
I triggeren `punktinfo_biu_trg` (defineret i #253) skal indsættes klausuler i stil med:

```
  IF this_andv = 'TEKST' AND :new.tekst IS NULL THEN
    RAISE_APPLICATION_ERROR(-20005, 'punktinfo.tekst må ikke være NULL ved anvendelsestypen "TEKST"');
  END IF;
```

Så burde der blive rejst en fejl hvis der ikke indsættes en tekst i et punktinfo med anvendelsen "tekst". Tilsvarende kan laves for tal.
