### ISSUE TITLE
Mere generel brugerstyring

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#257]
I #256 indføres simpel brugerstyring på en lettere hacky måde, ved at præfikse tabelnavne med fire_adm. Dette giver, for produktions- og testdatabaserne, korrekt opførsel, ligegyldigt hvilket brugerid man logger ind med.

Det samme er imidlertid ikke tilfældet for testsuiten, der bruger en separat databaseinstans og logger ind som bruger `fire` på server `localhost`. Derfor er der indlagt mønstergenkendelse i #256, som genkender testsuite`bruger`/`server`kombinationen, og udelader præfiksingen i det tilfælde.

Det kan gøres mere generelt, men jeg savner indtil videre en klokkeklar use-case til at støtte formgivningen af løsningen: For omfattende generalitet fører til bloat, for lidt til knækkede tånegle. Mulige veje kan diskuteres herunder.

**Comment by kbevers** [comment]
> Det kan gøres mere generelt, men jeg savner indtil videre en klokkeklar use-case til at støtte formgivningen af løsningen: For omfattende generalitet fører til bloat, for lidt til knækkede tånegle.

Jeg ser det lige omvendt: Hardcodede løsninger fører til bloat. I det store hele betyder det ikke alverden men jeg synes nu altså der er en pæn og lige til måde at gøre det her. Se #258. Fordelen her er at produktionskoden ikke kender noget til testkoden og da det er temmelig klart defineret hvornår vi befinder os i hvilket scenarie (`FireDb` eller `TestFireDb`) kan vi lige så godt udnytte det.

**Comment by busstoptaktik** [comment]
> Jeg ser det lige omvendt: Hardcodede løsninger fører til bloat.

Læs igen: Der står noget om både *for generel* og om *for snæver* kode.

Så der er *ikke* nogen "omvendt" situation i syne her: Mit statement (som jeg også brugte x antal sider på at elaborere over i mit PhDarbejde) er netop *sin egen omvendte*: Med mindre du har klare use cases til at guide formgivningen, så *generaliser indtil du når midten*. Det er en generalisering af Knuths statement om "premature optimization is the root of all evil", som netop ikke udsiger at optimering er slemt i sig selv - men den er slem når den kommer uden bagvedliggende substans:

* For tidlig generalisering, uden tilstrækkelige use-cases til at udpege den frugtbare retning, fører til bloat.
* Mangel på generalisering fører til kode med for snæver dækning.
* Just-in-time generalisering, guidet af faktiske use-cases fører til kode med både dækning og retning.

Pointen er, på den ene side at være klar til at håndtere ikke-håndterede cases når de dukker op og, på den anden side, at skubbe den opdukning så langt ud i fremtiden at den lære man skal drage af casen(e) gerne skulle være klar og tydelig når man når til den.

Hvad generalitet angår er din løsning ikke mere vidtgående end min - men den eliminerer en forgrening i konstruktoren, på bekostning af en global variabel. Forgreningen vil efter al sandsynlighed dukke op igen ved næste nødvendige generalisering - og så kan vi til den tid igen tage stilling til en vægtning mellem *state* og *flow*.

I min optik er det så det rette tidspunkt at tage det (vægtede) valg på. Men jeg er ikke imod at merge din løsning: Den kan jeg leve med lige så godt som med min egen. Den afspejler bare et andet udgangsvalg, og understreger derved også min pointe om at uden use cases generaliserer man i blinde: På nuværende tidspunkt er state lige så godt som flow. Ved næste løsningsiteration kan det være at en af dem (eller en passende vægtning) viser sig mest frugtbar.

**Comment by kbevers** [comment]
Lukket med #310
