### ISSUE TITLE
Fjern majoriteten af indset_* API-funktioner 

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#263]
Det har vist sig i praksis at være langt mere effektivt at lave indsættelser i databasen med afsæt i sagsevents. Altså, tilknyt diverse objekter til en sagshændelse som da indlæses med `FireDb.indset_sagsevent()`. SQLAlchemy klarer resten og fylder de tilknyttede objekter ind i de rette tabeller.

Denne tilgang er bedre, da den understøtter princippet om at alt relateret til en bestemt sagshændelse tilføjes i et og samme database commit. Det sikres på denne måde. Samtidigt kan cirka 10 `indset_*` funktioner fjernes fra API-overfladen. Funktionaliteten i de enkelte `indset_` funktioner skal så vidt det giver mening overføres til `indset_sagsevent()`.

Et eksempel på udradering af en `indset_` funktion er givet i #264

**Comment by busstoptaktik** [comment]
Det er helt klart den rigtige vej, men jf #259 er der stadig noget som ikke spiller, og som er svært at teste.

**Comment by kbevers** [comment]
Jeg har ikke haft tid til at dykke ned i hvad årsagen til #259 er endnu. Måske er vi heldige at det løser sig selv når #264 er merget ind men det skal vi nok ikke forvente. En mulighed kan også være at triggers på FIRE databasen ikke er helt up to date med hvad der er defineret i DDL i master.

Et forslag til at blive klogere på problemet er at slå SQLAlchemy debugging til, så du kan se alle SQL udtryk der sendes til databasen. Af og til bliver man klogere.

**Comment by busstoptaktik** [comment]
... hvordan med fx en iterabel over flere koordinater, for flere punkter, og hvor der indsættes flere tilfælde af den samme koordinattype til samme punkt på en gang (fx ilægning af hele tidsserier)?

**Comment by kbevers** [comment]
Jeg er ikke sikker på om databasen vil afvise det eller ej, men der sker i hvert fald det at vi ender med `koordinat1.sagseventfraid == koordinat2.sagseventfraid == koordinat3.sagseventfraid == ...` hvis de indsættes under samme sagsevent. Jeg tror det som minimum kan skabe noget forvirring, måske det der er værre men jeg har ikke tænkt specielt grundigt over det.

**Comment by busstoptaktik** [comment]
Det er nok bare en sag om at *beslutte* at nye tidsseriekoordinater indsættes "tidsskridtvis", så alle stationskoordinater til t=T indsættes under en hændelse.

Det vil også være det naturlige at gøre for nye koordinater, fordi de beregnes uge-for-uge (eller 5D-kampagne-for-5D-kampagne). Men for eksisterende tidsserier er det jo mest naturligt at tage dem punkt-for-punkt.

Det skal vi så bare lade være med :-)
