### ISSUE TITLE
fire niv regn: Html-rapport overskrives

### ISSUE THREAD

**Issue by majbrittws** [Kortforsyningen/FIRE#268]
Ved gentagne kørsler af niv regn, overskrives html-rapporten. Det vil være smart at få gemt kontrolberegningens html separat, og så kan de andre kørsler/endelige beregninger sådan set godt overskrives.

**Comment by kbevers** [comment]
God ide. Har du mod på at fikse det selv? Så vidt jeg kan se er det cirka her

https://github.com/Kortforsyningen/FIRE/blob/51c8695bfa8c28e59f502599ec54ae4dd8e355c9/fire/cli/niv/regn.py#L219-L232

der skal laves et par småændringer. En nem løsning er at bruge dato+klokkeslæt i filnavnet.

**Comment by majbrittws** [comment]
Jow, jeg ser på det så.

**Comment by busstoptaktik** [comment]
Lukket med #273
