### ISSUE TITLE
Udskift xlrd med openpyxl

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#281]
Jf. #278:

`xlrd` efter version 1.2.0 kan ikke læse `.xlsx`-filer (se [denne](https://stackoverflow.com/questions/65250207/pandas-cannot-open-an-excel-xlsx-file) beskrivelse henne på StackOverflow).

Udskift derfor `xlrd` med `openpyxl`.

**Comment by kbevers** [comment]
Tilsyneladende er `openpyxl` standard engine i Pandas fra version 1.2.0 og frem, så måske er det tilstrækkeligt med en pandas>=1.2.0 constraint i condamiljøet?

**Comment by busstoptaktik** [comment]
Ja, men der var et andet problem med 1.2.0 tidligere sidste år: Jeg skal lige komme i tanke om hvad problemet var/er, og om det evt er løst eller blevet irrelevant
