### ISSUE TITLE
Opgrader QGIS til 3.16

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#282]
QGIS 3.16 blev frigivet i oktober 2020, og er ny LTR 4 måneder derefter, dvs. fra slutningen af februar 2021, hvis jeg fatter QGIS-releaselogikken korrekt.

**Comment by busstoptaktik** [comment]
@kbevers : Jeg har kørt 3.16 et par dage nu, uden problemer. Jeg synes vi skal vælge den som kanonisk version for release 1.0.0. Har du noget at indvende mod det?

**Comment by kbevers** [comment]
Nej, det lyder fint

**Comment by busstoptaktik** [comment]
Lukker, da dette indgår i #290
