### ISSUE TITLE
HOWTO-release

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#304]
(dette issue er delvist brækket ud af #290) 

### Problemet

Release management er ikke en kunstart for folk med imperfekt hukommelse. Det gør i praksis processen mere konsistent hvis man har en opskrift at kravle efter. HOWTO-release.md er stedet for den slags.

#### Opdatering af semantiske versioner

I #290 og #291 løser vi problemet med inkompatibiliteter når vi har anført ingen, eller kun minimumsversioner i miljødefinitionsfilerne `environment.yml` og `environment-dev.yml`.

For at undgå at den ædle bitråddenskab skal angribe kodebasen er det vigtigt at vi løbende opdaterer versionsangivelserne i miljødefinitionsfilerne. Derfor skal der ligge en opgave af denne art som en del af release management (som jeg ville være fristet til at kalde det lige så mundrette "udgivelsesledelse" eller "udgivelseshåndtering"). Fx en notits om at *2 uger før afslutningen af en udviklingscyklus oprettes et "opdater conda-versioner" issue, og næste milepæl sættes til at afhænge af dette issues afklaring.*

### Luskehiste

- [x] Beskriv versionsvedligeholdelsesfremgangsmåden i `HOWTO_RELEASE.md`
- [ ] Beskriv dit og dat
- [ ]  .. og dut

**Comment by busstoptaktik** [comment]
@kbevers - dit, dat og dut (som jeg antager dækker over "fortæl folk at der er en ny (a)version klar og hvordan de kan få fingre i den) er  da vist inkluderet i den nuværende `HOWTORELEASE.md`. I så fald kan denne pind vel lukkes?

**Comment by kbevers** [comment]
Altså, der står ikke rigtigt noget om det med at teste et opdateret conda miljø af noget tid inden release. Men jeg tror egentligt også det er bedre at lade noget CI prøve det af automatisk i stedet for at vi selv glemmer det.
