### ISSUE TITLE
Luk Post-MVP-projekt

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#336]
Vi *er* i gang med Post-MVP, men kun/primært mht. den nivellementsergonomiske side. Jeg foreslår at vi lukker [Post-MVP](https://github.com/Kortforsyningen/FIRE/projects/1)-projektet og flytter pindene til (i første omgang) nyoprettede milestones for version 1.x og 2.0. Fra 1.x kan de så flyttes videre til 1.1, 1.2 etc. efterhånden som elementerne bliver prioriterede af projektejer og omegn.

**Comment by kbevers** [comment]
God ide. Jeg er generelt ikke fan af projektkonceptet her på GitHub, så thumbs up her fra.

**Comment by busstoptaktik** [comment]
- [ ]  Milepæle for 1.x og 2.0 oprettet.
- [ ] Alle projektelementer flyttet til 1.x eller 2.0.
- [ ] Projekt lukket.
