### ISSUE TITLE
Mærkelige deltakoter efter beregning

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#353]
Nedenstående beregning virker umiddelbart forkert da delta koterne for 51-01-* punkterne er præcis den samme. Tallene fra Gama resultatfilen ser dog ud til at passe med hvad der indlæses i regnearket. Tilhørende regneark er vedhæftet så der kan regnes efter.

![image](https://user-images.githubusercontent.com/13132571/109304474-a2d26380-783c-11eb-9cd1-c8636a642f6a.png)

[2020_5D_KDI_HESNAES.xlsx](https://github.com/Kortforsyningen/FIRE/files/6049828/2020_5D_KDI_HESNAES.xlsx)

**Comment by busstoptaktik** [comment]
Årsagen til det sære resultat er at jeg for (cirka) halvanden måned siden benyttede samme inputfil til at generere en par nye koter i forbindelse med test af Helles overføringsprogrammel.

Jeg fulgte Renés vejledning om hvilke punkter der skulle fastholdes (`G.I.2111` til kontrolberegning og `G.I.2111` og `G.I.2112` til endelig beregning), og lagde slutresultatet i `FIRETEST`. 

Beregningen i det ovenfor vedlagte regneark er en kontrolberegning med `G.I.2111` fastholdt, men da `G.I.2111` og `G.I.2112` begge to kun er forbundne med resten af nettet gennem `52-1-9053`, så er resultatet af at holde det ekstra punkt fast bare at vi får forskudt hele resten af nettet med en fast faktor: For nettet ser det ud som om vi bare holder et enkelt punkt fast. Et punkt som ligger et sted længere ude end `52-1-9053`, og som har en kote svarende til middelkoten af `G.I.2111` og `G.I.2112`. Vi kunne kalde det for `G.I.2111½` :-)

Jeg har checket det for `52-1-9051`. Det har den opdaterede kote (baseret på målinger fra december 2020) i testdatabasen, og den oprindelige kote fra 2018 i produktionsdatabasen:

```sh
> fire info punkt --db prod 52-1-9051

--- KOORDINATER ---
* 2018-02-01 16:16  EPSG:5799       n 1.49928 (0)
* 2005-10-06 14:24  DK:GI44         n 1.58300 (0)

> fire info punkt --db test 52-1-9051

--- KOORDINATER ---
* 2020-12-10 11:28  EPSG:5799       n 1.50105 (1)
* 2005-10-06 14:24  DK:GI44         n 1.58300 (0)
```

Jeg antager at dette løser mysteriet - og lukker denne pind.
