### ISSUE TITLE
Udvidet observationskontrol, udvidet observationer.geojson

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#366]
Det ville være en fordel at kontrollere observationssæt for at der både er foretaget frem og tilbagemåling, og advare hvis det ikke er tilfældet.

Oplysning om manglende returmåling tilføjes i `observationer.geojson`

**Comment by kbevers** [comment]
Oprindeligt issue justeret lidt, så det kun vedrører kontrol af frem/tilbage målinger og afrapportering af dette i geojsonfilen. Delen om observationstype (der er simplere at løse) flyttet til https://github.com/Kortforsyningen/FIRE/issues/374 .
