### ISSUE TITLE
Giv mulighed for at angive reviderede lokationskoordinater som UTM

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#380]
I den nuværende arbejdsgang, hvor VisFix stadig spiller en rolle er det praktisk at kunne anføre lokationskoordinater som UTM i revisionsarket. Derfor bør der indsættes et kald til `normaliser_lokationskoordinat()` i linje 508 her:  

https://github.com/Kortforsyningen/FIRE/blob/849a360816c78c30c0636b480a79bfc2e48ff651/fire/cli/niv/_il%C3%A6g_revision.py#L503-L509

Det fordrer dog at man konsekvent arbejder i UTM zone 32 - også når man er øst for Roskilde. @ReneTandsbjerg - er det tilfældet?

I modsat fald skal heuristikken modificeres, men jeg tror godt det kan lade sig gøre (for DK)

**Comment by ReneTandsbjerg** [comment]
Jeg har talt med @Palle-N omkring UTM zone 32/33 og han mente at der i sin tid, der blev det lavet sådan at visfix selv kunne skelne i hvilken zone man var. så jeg vil ikke umiddelbart ligge hovedet på blokken, men det er vel ikke den store flytning set i lyset af vi jo sætter en lokation indenfor 1-2 meter. Hvad siger du @Palle-N

**Comment by kbevers** [comment]
@ReneTandsbjerg Kan du ikke med visfix prøve at finde en UTM koordinat på et fikspunkt i København? Så kan vi lige kontrollere om den kommer ud som zone 32 eller 33. Det er vist den nemmeste måde at få afklaring på det.

**Comment by ReneTandsbjerg** [comment]
Jeg har tjekket en lokations fil fra Bornholm 2014 og det står i headeren at det er i zone 32, har også prøvet at digitalisere med visfix i kbh. samme resultat at headeren i lokations filen er allerede bestemt på forhånd , men det fortæller os jo ikke om vi så aktivt skal ind og ændre i headeren eller om refgeo selv fandt ud af det altså er i zone 33.  Har du andre gode ideer @kbevers

**Comment by ReneTandsbjerg** [comment]
Selv koordinaterne i beregningen for Bornholm er i 32

**Comment by kbevers** [comment]
Den eneste gode ide jeg har det er at få en koordinat på et punkt i nærheden af Københeden via visfix. Det du er kommet frem til nu antyder jo at zone 32 bruges men det vil være rart at bekræfte det med sikkerhed. Det kan en koordinat lynhurtigt afgøre.

Kan man klikke på kortet i visfix og få en koordinat frem for det sted? Hvis det er muligt, så klik på Rundetårn og skriv koordinaten her :-)

**Comment by kbevers** [comment]
Jævnfør snak med opmålingsteamet tidligere i dag kom vi frem til at det giver mest mening hvis lokationskoordinaten altid angives som UTM koordinater i revisionsregnearket. Både ved udtræk og når ny indtastes. Der er et par årsager til dette:

1. visfix-programmet i målerbilerne kan kun UTM
2. Det er nemmere at vurdere forskelle på UTM-koordinater i meter frem for geografiske koordinater i grader (endda langt ud i decimalerne)

**Comment by busstoptaktik** [comment]
> ... det giver mest mening hvis lokationskoordinaten altid angives som UTM koordinater i revisionsregnearket

Det er svært at være uenig i!

**Comment by ReneTandsbjerg** [comment]
> Den eneste gode ide jeg har det er at få en koordinat på et punkt i nærheden af Københeden via visfix. Det du er kommet frem til nu antyder jo at zone 32 bruges men det vil være rart at bekræfte det med sikkerhed. Det kan en koordinat lynhurtigt afgøre.
> 
> Kan man klikke på kortet i visfix og få en koordinat frem for det sted? Hvis det er muligt, så klik på Rundetårn og skriv koordinaten her :-)

6176413.9 m  724793.0 m
![20210419_143305](https://user-images.githubusercontent.com/78353923/115237791-43e2e980-a11d-11eb-84aa-1d39443925f4.jpg)

**Comment by kbevers** [comment]
Tak! Det er klart en utm zone 32 koordinat. Det siger programmet jo også så fint. Lidt mærkeligt at koordinaten skrives i (northing, easting) rækkefølge, men okay, det er da til at finde ud af.

**Comment by busstoptaktik** [comment]
> Lidt mærkeligt at koordinaten skrives i (northing, easting) rækkefølge

Det er nu ikke så mærkeligt: Dels er det den traditionelt anvendte akserækkefølge (jf KMSTRANS), dels er det **EPSG:3044**, som påkrævet iflg. INSPIRE. Det er kun DKTM1,2,3,4 der anvender easting-før-northing.

**Comment by kbevers** [comment]
Nå ja, EPSG:3044 er jo også i omløb. Den er ret dum, da de ting vi slipper ud i det fri under den EPSG-kode faktisk kommer med EPSG:25832 akserækkefølge alligevel. Det resulterer ofte i nogle uheldige nultransformationer fx når rasterdata anvendes.

Men nok om det. Vi må altså forvente at se begge akserækkefølger i det fri. Så enten skal vi lægge os fast på en fast konvention (fx nord først, så øst) eller angive "N" og "Ø" efter den enkelte værdi. Sidstnævnte gør vi nu men det bruges vist kun til at angive øst/vest eller nord/syd retning og ikke afgøre hvad der er længdegrad og hvad der er breddegrad.

**Comment by busstoptaktik** [comment]
> Så enten skal vi lægge os fast på en fast konvention...

Jeg er i gang med at løse problemet på mere generel vis. Det bliver `normaliser_placeringskoordinat()` der kommer til at trække det tunge læs. Den bliver i samme ombæring omdøbt til `normaliser_lokationskoordinat()`, så den kommer i overensstemmelse med den øvrige sprogbrug. Jeg ved ikke hvad jeg havde for en mental nedsmeltning, da jeg navngav den en gang i ældre stenalder.

**Comment by busstoptaktik** [comment]
> EPSG:3044 er jo også i omløb...

@heidivanparys har i øvrigt, med flittig henvisning til PROJ, overbevist rette vedkommende højere magter på JRC Ispra om at EPSG:258xx også er OK. Men indtil videre er INSPIRE-data altså i 30[08+xx]
