### ISSUE TITLE
Lad skriv_ark() fjerne "nan" i tekstfelter

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#386]
Med #382 bliver "nan" i tekstfelter rettet til "" under indlæsning. Det bør vi nok også gøre når vi skriver nye faneblade.

**Comment by kbevers** [comment]
Er der nogen realistiske scenarier hvor vi generer en nan-værdi i en celle der skal skrives? Og kommer den i så fald ikke bare til at fremstå som en tom celle i regnearket? Måske kan vi spare en hel linje kode ved ikke at lave denne ændring :-)

**Comment by busstoptaktik** [comment]
Der er i hvert fald et par steder, hvor `replace("nan", "")` kaldes før `skriv_ark()`, men om det er rester fra tidligere, overforsigtighed, eller reelt nødvendigt er jeg ikke sikker på.

**Comment by kbevers** [comment]
Okay, i så fald giver det jo fin mening at flytte de kald til et centralt sted

**Comment by busstoptaktik** [comment]
```sh
(fire-dev) $ git grep replace(\"nan\"
fire/cli/niv/__init__.py:            .replace("nan", "")
fire/cli/niv/_ilæg_nye_koter.py":            ny_punktoversigt = ny_punktoversigt.replace("nan", "")
"fire/cli/niv/_ilæg_observationer.py":            observationer = observationer.replace("nan", "")
```

... så det ser ud som om vi kan eliminere 2 linjer ved at centralisere med en :-)
