### ISSUE TITLE
Eliminer fire niv ilæg_nye_punkter

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#387]
`ilæg_nye_punkter` klares nu med en OPRET-række i punktrevisionsarket.

**Comment by kbevers** [comment]
Det er jeg ikke overbevist om er en god ide. At bruge OPRET funktionaliteten i revisionsregnearket kræver en hel del mere manuel indtastning end den nuværende løsning med `ilæg-nye-punkter` og det tilsvarende faneblad. Der skal skrives lokationskoordinat, ATTR:beskrivelse, AFM:xxxx og ATTR:højde_over_terræn samt de tilhørende værdier. Det bliver meget tasten i forhold til bare at indsætte værdierne. Det er desuden svært at putte en skabelon til formålet med i revisionsarket så man skal måske også huske hvilke punktinfo der skal med.

**Comment by busstoptaktik** [comment]
Det ser ud som om jeg momentant har mistet overblikket i anledning af ikke at kunne finde et "nye punkter" faneblad. OPRET i punktrevisionsarket blev indført for at kunne generere testdata til deltaoverførsler.

**Comment by kbevers** [comment]
> OPRET i punktrevisionsarket blev indført for at kunne generere testdata til deltaoverførsler.

Præcis. Funktionen har også værdi i andre sammenhænge udenfor det kommunale vedligehold. Det skal bare dokumenteres så vi kan finde ud af det når behovet opstår.
