### ISSUE TITLE
fire niv udtræk-revision: angiv lokationskoordinat som UTM zone 32 

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#388]
Går hånd i hånd med https://github.com/Kortforsyningen/FIRE/issues/380, specifikt i forhold til https://github.com/Kortforsyningen/FIRE/issues/380#issuecomment-822417342. Kort sagt, det er nemmere for menneskeøjne at finde grovfejl mellem to UTM-koordinater versus den geografiske gradependant.

**Comment by busstoptaktik** [comment]
@kbevers  denne er så vidt jeg kan se, ligesom #380, lukket med #394. Genåbn hvis du er uenig.
