### ISSUE TITLE
fire niv ilæg-revision: Indsæt ikke nye punktinfo hvis "ny værdi" er magen til eksisterende værdi

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#390]
Hvis indholdet af "talværdi" eller "tekstværdi" er identisk med "ny værdi" skal denne ikke oprettes som punktinfo, da det bare er at duplikere data der allerede er registreret. Situationen kan opstå ved en fejl hvis man kopiere indholdet fra fx "tekstværdi" til "ny værdi" og glemmer at rette teksten til.

**Comment by busstoptaktik** [comment]
Det er ligetil for tekstværdier, men ikke ganske så ligetil for talværdier (det er en af de to grunde til at der er både en tal- og en tekstsøjle for eksisterende data): Excel vil ikke i alle tilfælde kopiere "tal-som-tekst" på samme måde som pandas vil oversætte den anden vej, og geodætisk set er det ikke altid oplagt om det er en absolut eller relativ afvigelse, der er mest relevant at teste på.

I første omgang skal vi nok bare checke  `tekstværdi==ny værdi` for tekstværdier (trivielt) og så fx `fabs(talværdi - float(ny værdi)) < 1e-12)` og så justere på skæringsværdien, hvis der kommer for mange falsk positive (eller negative, afhængig af hvilken side af hegnet man kigger fra).

Jeg tror det vil fungere, men vi skal være opmærksomme.
