### ISSUE TITLE
Bør brug af ATTR:bemærkning udgå?

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#392]
`ATTR:bemærkning` bruges tilsyneladende kun til at angive årstal og person i forbindelse med punktrevision. Denne information er automatisk registreret i FIRE i kraft af Sagsevents og tilhørende sagsbehandler og opdatering af `ATTR:bemærkning` under punktrevision kan da udelades. Der melder sig dog et spørgsmål: Er informationen om hvornår og hvem der udførte seneste punktrevision overhovedet nyttig? @ReneTandsbjerg @rebeccakol @Palle-N @jsnSDFE? 

Hvis målernes svar er ja, hvordan skal den i så fald præsenteres i revisionsregnearket hvis ikke `ATTR:bemærkning` bruges? Og skal det så være seneste uspecificerede ændring på punktet eller en specifikt ændring fx lokationskoordinat der betragtes som sidste revisionstidspunkt?

**Comment by Palle-N** [comment]
Jeg bruger det til kontrol ifm. punktrevision. Når man har afsluttet en revision bør alle tidligere initialer og revisionsår være udskiftet, er der nogen tilbage af de gamle er det fordi punktet ikke er besøgt...
Vi har indtil nu ikke udskiftet initialer/årstal hvis vi bare har foretaget en lokationsændring, det er kun blevet opdateret ifm. en punktrevision, altså hvor tekst og mål tjekkes/rettes.

**Comment by kbevers** [comment]
> Jeg bruger det til kontrol ifm. punktrevision. Når man har afsluttet en revision bør alle tidligere initialer og revisionsår være udskiftet, er der nogen tilbage af de gamle er det fordi punktet ikke er besøgt...

@Palle-N Hvad nu hvis du/I bruger kolonnen "ikke besøgt" aktivt i revisionen? Altså, når I har været forbi et punkt så fjerner i krydset under "ikke besøgt" for at markere at I har været der. Det er derfor den er der.

**Comment by Palle-N** [comment]
Det er en fin erstatning for den kontrol jeg hidtil har benyttet mig af.
Men oplysningen om hvornår punktet er revideret sidst synes jeg er nyttig, initialerne er mindre væsentlige, dem bruger vi målere indbyrdes til at "drille" hinanden med hvis vi finder fejl i tidligere revision, men det forklarer også nogen gange hvorfor en tekst ikke lige overholder retningslinjerne, her tænker jeg på vores ufaglærte assistenter.

**Comment by ReneTandsbjerg** [comment]
Jeg syntes fremadrettet et årstal der indikere hvornår punktet sidst har været besøgt er nyttigt. 
Jeg er dog en smule i tvivl om det der skrives i ATTR:bemærkning som f.eks kunne være (Ej opgravet i 2021) eller en anden nyttig bemærkning, om den kommer med ud i Valdemar? Eller skal sådan en info stå direkte i beskrivelsen?

**Comment by kbevers** [comment]
@Palle-N @ReneTandsbjerg Kan I ikke prøve at forklare hvorfor det er nyttigt med tidspunktet for sidste revision? Jeg betvivler ikke at det er nyttigt, jeg skal bare forstå hvorfor. Det gør det nemmere at finde den bedste løsning.

> Jeg er dog en smule i tvivl om det der skrives i ATTR:bemærkning som f.eks kunne være (Ej opgravet i 2021) eller en anden nyttig bemærkning, om den kommer med ud i Valdemar? Eller skal sådan en info stå direkte i beskrivelsen?

ATTR:bemærkning er til intern brug, ATTR:beskrivelse kommer ud på Valdemar.

**Comment by Palle-N** [comment]
Som skrevet tidligere beskrevet erstatter det at fjerne krydset i "Ikke besøgt" fint min kontrolfunktion.

Jeg har oplevet et par gange at få udleveret det forkerte materiale til en punktrevision. De fleste kommuner er delt i 2 dele sådan at vi reviderer hvert 6. år. Ved en fejl har jeg fået materiale for området der var revideret 3 år tidligere, og ikke 6 år. Den fejl opdagede jeg med det samme ved at der stod revisionsår.

Jeg har også oplevet at få materiale for en kommune hvor der i aftalen står at det er kommunen selv der foretager revision. på den første revisionsdag undrer jeg mig over det er samtlige tekster der står kommunens navn sammen med revisionsår, og tjekker op på kontrakten. Det kunne ha´ resulteret i flere ugers arbejde som ikke var nødvendigt, hvis oplysningen ikke havde stået der.

Vi taler med rigtig mange personer ifm. punktrevision, og ofte bliver der spurgt til "hvor tit vi kommer, for vi var der jo sidste år", og så kan man ganske hurtigt fortælle at "det var uge dit i år dat vi var der sidst, og det var i øvrigt mig du talte med dengang"

Nyttig oplysning.. ja jeg synes den er nyttig, eller i hvert tilfælde rar at ha´, og mener oplysningen står rigtig fint som en ATTR: bemærkning til intern brug.

**Comment by kbevers** [comment]
Tak Palle. Jeg synes vi skal holde fast i ATTR:bemærkning. Det er svært at finde en simpel automatisk erstatning for den, og den giver også mulighed for at tilføje lidt ekstra hvis det er nødvendigt.
