### ISSUE TITLE
fire niv ilæg-revision: Fjern dobbelte punktummer og mellemrum fra tekst i "ny værdi"

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#393]
Det hænder at der smutter et ekstra tegn med under indtastningen. Stavekontrollen i Excel fanger desværre ikke den slags så vi kan hjælper den lidt på vej. 

Stavekontrollen er i øvrigt ellers god til at fange fejlskrevne ord og bør bruges inden revision indlæses i databasen, så det sikres at punktbeskrivelser der offentliggøres ikke indeholder åbenlyse fejl.

**Comment by busstoptaktik** [comment]
Måske vil det også være smart at fjerne whitespace i start og slut af alt, der skrives til databasen - som [her](https://github.com/Kortforsyningen/FIRE/blob/c09b19a2d94da7e46cfe70b25be9eacd24e9ea6c/fire/cli/niv/_l%C3%A6s_observationer.py#L295-L296)

**Comment by kbevers** [comment]
Ja, det vil være meget passende. Jeg har set flere eksempler hvor unødige linjeskift i starten af en tekst kommer med.

**Comment by busstoptaktik** [comment]
jæb

**Comment by kbevers** [comment]
Jeg tager det med i #398 som nu bliver holdeplads for alle ændringer til ilæg-revision. Satser på at nå gennem det hele inden dagen er omme.
