### ISSUE TITLE
fire niv ilæg-revision: kontroller at vi skriver til det rigtige skema

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#400]
record-id bruges til at opdatere punktinformationer, så det kan gå meget galt hvis man (ved en fejl) forsøger at opdatere til `prod` med et revisionsark, der er hentet ud fra `test`

**Comment by kbevers** [comment]
Det gøres faktisk allerede nogle steder, fx i `fire niv luk-sag`:

https://github.com/Kortforsyningen/FIRE/blob/c09b19a2d94da7e46cfe70b25be9eacd24e9ea6c/fire/cli/niv/_luk_sag.py#L54-L58

Det bør selvfølgelig implementeres mere generelt. 

I forhold til at indlæse data fra test i prod så tror jeg man vil blive mødt af en fejl inden det kommer så vidt. Alle punkt-id'er er forskellige som det er nu. Det kan dog ikke forventes at være en permanent tilstand så noget må gøres.
