### ISSUE TITLE
Link til konfiguration mangler

### ISSUE THREAD

**Issue by larsnaesbye** [Kortforsyningen/FIRE#411]
Under mit sidste commit fik jeg forsøgt indsat et link til konfigurationsfilen under https://kortforsyningen.github.io/FIRE/installation.html#konfigurationsfil

Men linket virker ikke, så informationen om konfigurationsfilen er ikke åbenlys.

**Comment by kbevers** [comment]
Se #412

**Comment by larsnaesbye** [comment]
Jeg lukker den så.
