### ISSUE TITLE
ilæg-observationer - indsætter 0 observationer i db

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#421]
Problem med kommandoen ilæg-observationer.
Der skrives ingen observationer i prod db

Ilægning af observationer fra
Empty DataFrame
Columns: [Journal, Fra, Til, uuid]
Index: []
Skriver 0 observationer
Du indsætter nu 0 observationer i prod-databasen - er du sikker? (ja/NEJ):

[2021_DMI_ESBJERG_HAVN.xlsx](https://github.com/Kortforsyningen/FIRE/files/6494388/2021_DMI_ESBJERG_HAVN.xlsx)

**Comment by busstoptaktik** [comment]
Problemet ser ud til at være nogle drop-funktioner, der efter #382 ikke længere er nødvendige.  PR #423 ser ud til at løse problemet: Der skal bare slettes 6 linjer kode.
