### ISSUE TITLE
Beregningstidspunkt registreres forkert i regneark

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#425]
Fra @Palle-N:

> Der går et eller andet galt i ”Hvornår” kolonnen…?
>
> Har lige regnet det for 5 minutter siden.

![hvornaar](https://user-images.githubusercontent.com/13132571/118935754-28514580-b94c-11eb-825b-b1960eb8601c.jpg)

Af skærmbilledet fremgår det at computerens egen tid er sat korrekt. Resultaterne er skabt med `fire niv regn`.

**Comment by busstoptaktik** [comment]
Så vidt jeg husker bliver datoen sat til datoen for seneste observation: Det er jo det, der er det egentlige gyldighedstidspunkt.

**Comment by kbevers** [comment]
Det kunne være fint at få bekræftet i så fald. Det ville give god mening hvis det er er tilfældet. Det bør fremgå af dokumentationen så vi ikke skal undre os over det en anden gang.

Jeg synes dog det ser lidt mistænkeligt ud at alle observationer i så fald skulle være foretaget på præcis samme tidspunkt. Men det er måske fordi der ikke er tilstrækkeligt styr på hvornår observationerne er foretaget? Måske ser vi i virkeligheden observationernes registreringstidspunkt er.

**Comment by Palle-N** [comment]
Der er ingen observationer i denne beregning som er fra før d. 16.03.2021, og den sidste observation er foretaget 17.05.2021.
