### ISSUE TITLE
Manglende punkter ved udtræk-revision...

### ISSUE THREAD

**Issue by Palle-N** [Kortforsyningen/FIRE#434]
Hvad mon årsagen er til at tekster til følgende punktnumre ikke kommer med ved udtræk-revision. Jeg har lige forsøgt et ekstra udtræk, men de kommer ikke med, og jeg skal ha´ revideret teksten...

80-12-00821
80-12-00822

Så har jeg 2 naturlige fikspunkter jeg har konstateret tabt, hvordan gør jeg det...?

80-05-00002
80-09-00007

**Comment by busstoptaktik** [comment]
Det to punkter 80-12-821+822 kommer ikke med i revisionsudtrækket fordi de er mærket som MV-punkter (ATTR:MV_punkt). Det er jo nok en fejl: De er afmærkede med universalkalotter, så det lyder ikke som MV-punkter?

De to væltede skorstene, 80-05-00002 og 80-09-00007 kommer heller ikke med i revisionsarket fordi de er markerede som naturlige fikspunkter (AFM:naturlig).

**Spørgsmål:** Mener du at det vil være en fordel at få de naturlige fikspunkter med i revisionsarket? Der er ialt lige knapt 13000 af dem spredt over hele landet, så det er ikke fordi det vil fylde voldsomt op i et enkelt opmålingsdistrikt, og rettelsen i koden er triviel

Jeg sender dig en regnearksstump i epost af et specialudtræk med de fire punkter, som du kan klippe ind i bunden af dit eksisterende revisionsregneark og komme videre - for det bliver lidt bøvlet hvis du skal til at udtrække påny og dermed overskrive de ændringer du har indført.

**Comment by busstoptaktik** [comment]
Det ser ud til at der er en del 800-numre, der er markeret som MV-punkter. Det er næppe korrekt?

* Der er ialt 22524 punkter med landsnummer af formen herred-sogn-008xx
* 14158 af dem er markerede som GI-punkter
* 8048 af dem er markeret som MV-punkter
* 318 af dem er hverken markeret som GI eller MV
* Der er ikke noget overlap mellem dem, der er markerede som MV-punkter og dem, der er markerede som GI-punkter

@Palle-N og @mrlarshole: Hvordan er historikken her? Palle diagnosticerede problemet ved 80-12-821 hhv 80-12-822, men:

* 800-rækkerne bør jo være GI-punkter. Kan punkter historisk være registrerede som GI og MV på en gang?
* Bør vi slukke for `ATTR:MV_punkt` for de 8048 tilfælde i 800-rækkerne - og bør de i givet fald så erstattes med `ATTR:GI_punkt`?
* ... og hvad med de 318 punkter i 800-rækkerne, der hverken er GI eller MV?

```sql
with
    otte as (
        select punktid from punktinfo
        where infotypeid = 346 and tekst like '%-%-008%%' and registreringtil is null
    ),
    MV as (
        select punktid from punktinfo
        where infotypeid = 337 and registreringtil is null
    ),
    GI as (
        select punktid from punktinfo
        where infotypeid = 338 and registreringtil is null
    )
--
select count(otte.punktid) from

otte 
-- => 22524

otte inner join MV on otte.punktid=MV.punktid
-- => 8048

otte inner join GI on otte.punktid=GI.punktid
-- => 14158

otte inner join MV on otte.punktid=MV.punktid inner join GI on otte.punktid=GI.punktid
-- => 0

select count(*) from
(
    select * from otte
    minus
    select * from MV
    minus
    select * from GI
)
-- => 318
```

**Comment by Palle-N** [comment]
De naturlig fikspunkter fremgår af vores GIS program VisFix når vi kører i marken, så jeg tjekker altid om punktet eksisterer endnu når jeg nu alligevel kører lige forbi, ingen grund til de står som valide punkter i db når de måske har været tabtgået i årtier.
Men jeg tror jeg er den eneste som tjekker dem, og det er vel fordi at jeg har været her så længe at jeg faktisk har brugt dem flittigt da vi målte optisk triangulation.
Personligt synes jeg det vil være oplagt at ta´ dem med i udtrækket, hvis vi ikke kommer forbi ifm. punktrevision står de jo bare i arket som ikke besøgt. @ErikLysdal @ReneTandsbjerg @jsnSDFE @rebeccakol @busstoptaktik

**Comment by Palle-N** [comment]
Mht. hvad som er markeret som MV punkt, så har jeg ikke rigtig nogen viden om at nivellementskalotter og U-kalotter skulle være en del af MV nettet, men jeg er meget sikker på at alle af de 2 nævnte afmærkninger skal være markeret som GI-punkter...
@mrlarshole

**Comment by busstoptaktik** [comment]
> jeg tjekker altid om punktet eksisterer endnu når jeg nu alligevel kører lige forbi, ingen grund til de står som valide punkter i db når de måske har været tabtgået i årtier.

Ganske enig. Vi kan jo bare fjerne den linje kode, der frasorterer de naturlige fikspunkter, og så se om det er et reelt støjproblem at de kommer med på listerne. Hvis det viser sig at være tilfældet kan vi tage dem ud igen.

Som jeg husker det var det en mere eller mindre arbitrær beslutning, der førte til frasorteringen: @majbrittws og jeg sad en sen eftermiddag sidste forår og skulle have en "alt for lang" komplet liste skåret ned til noget, der var til at overkomme. Naturlige fikspunkter var så en af de grupper der kom med i "væk med dem"-listen. Det virkede efter hensigten: Listen blev kortere. Men hensigten var tydeligvis ikke perfekt gennemarbejdet :-)

Der er jo givetvis massevis af trianguleringsmål som er væltede de sidste mange år - lad os bare få dem tabtmeldt. De har vel oven i købet også den fordel at det ikke kræver nær-inspektion at konstatere deres status.

**Comment by mrlarshole** [comment]
Hej Thomas

Din optælling er farlig fordi nummerinterval inddelingen kun er vejledende og der er alle mulige mere eller mindre gode grunde til at der er afvigelser.
Derfor er det mest korrekte at tælle op på mv_status

Dine optællinger foregår på FIRE formoder jeg. Jeg har svært ved at genskabe dem i REFGEO.
Det skyldes sikkert forskellen mellem formen og antallet af kasser det var pakket ned i på REFGEO kontra form og antal på FIRE.
Der kan ikke søges på en streng ala: %-%-008%%.
Den avancerede nummerlæser på REFGEO tolkede nummeret til output ud fra kolonnerne i hvd_ref, hnr, snr, lbn, slt, suf men i kombination med type og region og ingen af dem kunne være NULL.
F.eks. læses hnr=0 som K ved nummertype 1 mens det ikke læses ved andre nummertyper.

Når du skriver: landsnummer af formen herred-sogn-008xx, må det være det der hedder nummertype 1 i HVD_REF.
Denne nummertype forekommer kun i region DK og FO. Jeg formoder at infotypeid er det der svarer til mv_status?

mv_status = 0 height network.
mv_status = 1 plane network, MV control point.
mv_status = 2 plane network, GI control point.
mv_status = 3 plane/height network, temporary control point.
mv_status = 4 navigation mark of any kind in plane network.
mv_status = 5 technical landmark in plane network.

Optælling f.eks.:
  select mv_status, count(*) from hvd_ref
  where typ=1 and lbn between 799 and 999
  group by mv_status order by 2;

MV_STATUS   COUNT(*)
0                           317
-1                         333
1                           9283
2                           14520

mv_status =0 er GI højde og alle sammen(undtagen 1) på Færøerne, så det er nok en del af en fornuftig forklaring.
mv_status=-1 er en tidligere benyttet måde at melde punkterne ude af systemet dog uden at slette dem. (glem dem)
mv_status=1 er fra hele landet dog ofte med en gammel oprettelsesdato, så mit gæt er at de er født sådan da systemerne var separate. Nogle er fra opmålingsdistrikt 199-01 hvilket er Tyskland her gjaldt egne regler.
Mv_status=2 er jo helt fint, men som sagt findes der flere i denne gruppe. F.eks findes der 748 unique lbn i kategorien.

Der kan kigges dybere i dette men jeg klapper lige hesten… ;0)

GI-plan har mv_status 2
Disse punkter er i landsnummersystemet normalt nummereret i intervallet 001-010 og 801-1000.
Visse steder er intervallet overskredet.

GI-koter mv_status 0:
Disse punkter er i landsnummersystemet normalt nummereret i intervallet 9000-9999.
Visse steder er intervallet overskredet.

MV-punkter mv_status 1:
De matrikulære fikspunkter er etableret af privatpraktiserende landinspektører i
forbindelse med matrikulære arbejder og kortlægningsopgaver i større målforhold.
Disse punkter er normalt nummereret i intervallet 011-800 og 1001-5500 i lands-
nummersystemet.

Mvh Lars

Fra: Thomas Knudsen ***@***.***>
Sendt: 8. juni 2021 11:35
Til: Kortforsyningen/FIRE ***@***.***>
Cc: Lars Hole ***@***.***>; Mention ***@***.***>
Emne: Re: [Kortforsyningen/FIRE] Manglende tekster ved udtræk-revision... (#434)


Det ser ud til at der er en del 800-numre, der er markeret som MV-punkter. Det er næppe korrekt?

  *   Der er ialt 22524 punkter med landsnummer af formen herred-sogn-008xx
  *   14158 af dem er markerede som GI-punkter
  *   8048 af dem er markeret som MV-punkter
  *   318 af dem er hverken markeret som GI eller MV
  *   Der er ikke noget overlap mellem dem, der er markerede som MV-punkter og dem, der er markerede som GI-punkter

@Palle-N<https://github.com/Palle-N> og @mrlarshole<https://github.com/mrlarshole>: Hvordan er historikken her? Palle diagnosticerede problemet ved 80-12-821 hhv 80-12-822, men:

  *   800-rækkerne bør jo være GI-punkter. Kan punkter historisk være registrerede som GI og MV på en gang?
  *   Bør vi slukke for ATTR:MV_punkt for de 8048 tilfælde i 800-rækkerne - og bør de i givet fald så erstattes med ATTR:GI_punkt?
  *   ... og hvad med de 318 punkter i 800-rækkerne, der hverken er GI eller MV?

with



    otte as (



        select punktid from punktinfo



        where infotypeid = 346 and tekst like '%-%-008%%' and registreringtil is null



    ),



    MV as (



        select punktid from punktinfo



        where infotypeid = 337 and registreringtil is null



    ),



    GI as (



        select punktid from punktinfo



        where infotypeid = 338 and registreringtil is null



    )



--



select count(otte.punktid) from







otte



-- => 22524







otte inner join MV on otte.punktid=MV.punktid



-- => 8048







otte inner join GI on otte.punktid=GI.punktid



-- => 14158







otte inner join MV on otte.punktid=MV.punktid inner join GI on otte.punktid=GI.punktid



-- => 0







select count(*) from



(



    select * from otte



    minus



    select * from MV



    minus



    select * from GI



)



-- => 318

**Comment by ReneTandsbjerg** [comment]
> De naturlig fikspunkter fremgår af vores GIS program VisFix når vi kører i marken, så jeg tjekker altid om punktet eksisterer endnu når jeg nu alligevel kører lige forbi, ingen grund til de står som valide punkter i db når de måske har været tabtgået i årtier.
> Men jeg tror jeg er den eneste som tjekker dem, og det er vel fordi at jeg har været her så længe at jeg faktisk har brugt dem flittigt da vi målte optisk triangulation.
> Personligt synes jeg det vil være oplagt at ta´ dem med i udtrækket, hvis vi ikke kommer forbi ifm. punktrevision står de jo bare i arket som ikke besøgt. @ErikLysdal @ReneTandsbjerg @jsnSDFE @rebeccakol @busstoptaktik

Jeg har ingen holdning til dem, så det gør fra eller til om de er med eller ej i udtræk.

**Comment by mrlarshole** [comment]
Jeg vil mene at det er en naturlig ting at når man laver punktrevision at man reviderer alle punkter som vi udstiller når man er i området.
Altså en naturlig del af opgaven for at få en så autentisk udstilling som muligt. Loggen viser at naturlige fikspunkter benyttes.

Et eksempel er en henvendelse jeg fik efter en præsentation af den nye Valdemar. En repræsentant for svæveflyver samfundet i DK fortalte at de på Valdemar var meget glade for at kunne finde koordinater på skorstene, antenner og andre højtragende elementer i landskabet.

Man kunne muligvis finde nogle af de samme i GeoDanmark data?
-men vi udstiller dem.

Mvh Lars

Fra: ReneTandsbjerg ***@***.***>
Sendt: 11. juni 2021 07:42
Til: Kortforsyningen/FIRE ***@***.***>
Cc: Lars Hole ***@***.***>; Mention ***@***.***>
Emne: Re: [Kortforsyningen/FIRE] Manglende punkter ved udtræk-revision... (#434)


De naturlig fikspunkter fremgår af vores GIS program VisFix når vi kører i marken, så jeg tjekker altid om punktet eksisterer endnu når jeg nu alligevel kører lige forbi, ingen grund til de står som valide punkter i db når de måske har været tabtgået i årtier.
Men jeg tror jeg er den eneste som tjekker dem, og det er vel fordi at jeg har været her så længe at jeg faktisk har brugt dem flittigt da vi målte optisk triangulation.
Personligt synes jeg det vil være oplagt at ta´ dem med i udtrækket, hvis vi ikke kommer forbi ifm. punktrevision står de jo bare i arket som ikke besøgt. @ErikLysdal<https://github.com/ErikLysdal> @ReneTandsbjerg<https://github.com/ReneTandsbjerg> @jsnSDFE<https://github.com/jsnSDFE> @rebeccakol<https://github.com/rebeccakol> @busstoptaktik<https://github.com/busstoptaktik>

Jeg har ingen holdning til dem, så det gør fra eller til om de er med eller ej i udtræk.

**Comment by kbevers** [comment]
> Jeg vil mene at det er en naturlig ting at når man laver punktrevision at man reviderer alle punkter som vi udstiller når man er i området.

Den betragtning er jeg enig i. Af de fire punkter herover er det kun de to naturlige der bliver udstillet i den gamle Valdemar. De kommer dog ikke ud på den nye af en eller anden grund som jeg ikke lige kan gennemskue. Lige hvad angår de to punkter er det vist ikke den store katastrofe men andre naturlige punkter kan I hvert fald blive udstillet den vej så jeg synes det giver god mening at medtage dem i revisionen. Så den ændring laver jeg lige. Så kan vi altid rulle den tilbage hvis det støjer for mig som Thomas foreslår.
