### ISSUE TITLE
Tidspunkt for fastholde koter ændres i endelig beregning

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#436]
Se eksempel i [doubleobs.xlsx](https://github.com/Kortforsyningen/FIRE/files/6616207/doubleobs.xlsx), hvor 48-02-09016 og 48-02-09045 er fastholdt i den endelig beregning (uden at være det i kontrolberegningen). Tidspunktet for disse to koter er det samme som alle de frie punkter selvom de har et andre tidspunkter tilknyttet sig i punktoversigten (2000-11-03 og 2018-02-05). Det tyder på at tidspunktet for de fastholdte i den endelige beregning læses fra kotelisten i kontrolberegningen, hvilket også bekræftes her https://github.com/Kortforsyningen/FIRE/blob/245c67598ac33cc2c3170fd8b4027d62b66b5702/fire/cli/niv/_regn.py#L56-L62
De skal naturligvis aflæses fra punktoversigten uanset om det er kontrol eller endelig beregning. Det kommer til at komplicerede logikken en anelse længere nede i filen.

Fastholdte koordinater indsættes ikke i databasen så skaden er begrænset. Det ser bare forkert ud med en ukorrekt dato på en fastholdt kote.

**Comment by kbevers** [comment]
Ved nærmere eftersyn viser det sig at problemet stikker en anelse dybere. Da observationerne der indgår i den endelige beregning tages fra fanebladet "kontrolberegning" ender alle delta t'er mellem gamle og nye koter med at blive nul, da koternes tidspunkt i kontrolberegningen afledes af observationernes tidspunkt. Resultatet er, at vi får uplift på 0.0 mm/år. 

Løsningen er formentligt at altid læse observationer osv fra fanebladet "punktoversigt" og så opdatere "Fasthold" kolonnen med indholdet fra fanebladet "Kontrolberegning". På den måde undgås problemet.

**Comment by busstoptaktik** [comment]
Hm - jeg synes lige jeg har haft fat i det der dt=0 problem.  Gælder det master eller 1.1.1?

**Comment by kbevers** [comment]
> Hm - jeg synes lige jeg har haft fat i det der dt=0 problem. Gælder det master eller 1.1.1?

Begge så vidt jeg kan se. Den rettelse du lavede i https://github.com/Kortforsyningen/FIRE/commit/38afd6d3756bc0318885982286bf63220a814fb8 tager ikke højde for at informationerne læses fra "kontrolberegnings"-fanebladet i den endelige beregning.

**Comment by busstoptaktik** [comment]
Ævferpævker :-)

**Comment by busstoptaktik** [comment]
Det var sgu en elegant løsning - og med indlagt forbedring af et par variabelnavne!
