### ISSUE TITLE
ATTR:gnss_egnet

### ISSUE THREAD

**Issue by ReneTandsbjerg** [Kortforsyningen/FIRE#438]
Jeg vil gerne ændre en attribut fra ATTR:gnss_egnet til ATTR:Ej_gnss_egnet

53-10-00804
    Retter punktinfo-element: ATTR:beskrivelse
    Slukker: ATTR:gnss_egnet
    ADVARSEL: Tekst i 'Ny værdi' identisk med udgangspunkt for AFM:3900.
    Retter punktinfo-element: ATTR:bemærkning
    ADVARSEL: Tekst i 'Ny værdi' identisk med udgangspunkt for IDENT:ekstern.
    * Ignorerer ukendt punktinformationstype 'ATTR:Ej_gnss_egnet'

[2021_FREDERIKSHAVN_NORD-revision.xlsx](https://github.com/Kortforsyningen/FIRE/files/6648678/2021_FREDERIKSHAVN_NORD-revision.xlsx)

**Comment by kbevers** [comment]
Det er ikke sådan det fungerer. Sæt kryds i "sluk"-kolonnen i stedet. Så fjernes ATTR:gnss_egnet.

**Comment by ReneTandsbjerg** [comment]
Det har jeg gjort. 
Men jeg har så tilføjet ATTR:Ej_gnss_egnet. 
Fordi punktet er omkranset af høje træer. 

Hvis ATTR:gnss_egnet fjernes
hvordan ved en bruger i marken at punktet som i dette tilfælde er en universalkalot, at det ikke længere er gnss_egnet?

**Comment by kbevers** [comment]
> Men jeg har så tilføjet ATTR:Ej_gnss_egnet.

Du kan ikke bare tilføje dine egne hjemmelavede attributter. Sorry :-)

> Hvis ATTR:gnss_egnet fjernes hvordan ved en bruger i marken at punktet som i dette tilfælde er en universalkalot, at det ikke længere er gnss_egnet?

Hvis ikke punkt ikke har ATTR:gnss_egnet, så må det antages at det ikke er egnet til GNSS opmåling. Hvis det tidligere har haft ATTR:gnss_egnet og det efterfølgende er fjernet kan det jo kun forstås som at punktet ikke længere er egnet til GNSS opmåling.
