### ISSUE TITLE
Kan ikke indsætte tabsmelding

### ISSUE THREAD

**Issue by mrlarshole** [Kortforsyningen/FIRE#459]
Ved tabsmelding laves udtræk og row oprettes med "ATTR: tabt" ved indsættelse findes ikke db ikke.
Gælder både ved test og prod. ini-fil kontrolleret. 
Følgende forsøgt uden held:
cd C:\fire\FIRE
git pull
git checkout 9c09ca9aa3ed476749a5c90

**Comment by kbevers** [comment]
Den hedder `ATTR:tabtgået`. Hvis du er i tvivl om hvilke typer der findes kan du selv se efter med `fire info infotype`, fx:

```
(fire) C:\dev\fire>fire info infotype ATTR
"ATTR" matcher følgende punktinfotyper:

ATTR:GI_punkt
ATTR:MV_punkt
ATTR:aerotriangulationspunkt
ATTR:bemærkning
ATTR:beskadiget
ATTR:beskrivelse
ATTR:ekstern
ATTR:fundamentalpunkt
ATTR:gnss_egnet
ATTR:hjælpepunkt
ATTR:højdefikspunkt
ATTR:muligt_datumstabil
ATTR:restricted
ATTR:sømærke
ATTR:tabtgået
ATTR:teknikpunkt
ATTR:tinglysningsnr
ATTR:vandstandsmåler
```

**Comment by mrlarshole** [comment]
Jeg kan fortsat ikke tabsmelde i fire. Hjælp!

**Comment by kbevers** [comment]
Prøv lige at vedhæfte din projektfil, så må vi prøve at dykke ned i det

**Comment by mrlarshole** [comment]
[tabtfikspunkt.xlsx](https://github.com/Kortforsyningen/FIRE/files/7209328/tabtfikspunkt.xlsx)
[tabsmelding.xlsx](https://github.com/Kortforsyningen/FIRE/files/7209329/tabsmelding.xlsx)

**Comment by mrlarshole** [comment]
Jeg kan ikke beskrive hvad der gik galt, ud over at meddelelsen på skærmen var at db ikke blev fundet da projektfil skulle indsættes. kbevers var med i forløbet da jeg er under oplæring og han ville fintænke på problemet.
Hvis denne beskrivelse ikke er nok vil jeg anbefale at vi sammen prøver igen.

**Comment by kbevers** [comment]
Ja, jeg husker nu hvad problemet var. Jeg skal også lige have en kopi af `tabtfikspunkt-revision.xlsx` og `tabsmelding-revision.xlsx` da det er der informationer om hvilke punkter der skal tabmeldes findes. Så vidt jeg husker var fejlen ikke reproducerbar hos mig men jeg vil gerne lige give det et forsøg igen.

**Comment by mrlarshole** [comment]
Disse filer har jeg ikke, måske vi bare skal lave nogle nye. Starte forfra?

**Comment by kbevers** [comment]
Ja, prøv lige forfra. Hvis alt fungerer skal du kunne gøre noget i stil med nedenstående. Tilføj `ATTR:tabtgået` til punkterne efter udtræk-revision kommandoen.

```
fire niv opret-sag xyz
fire niv udtræk-revision xyz punkt1 punkt2 ...
fire niv ilæg-revision xyz
fire niv luk-sag xyz
```

**Comment by mrlarshole** [comment]
Tak Kristian, det vil jeg gøre.

**Comment by busstoptaktik** [comment]
... og når det så er konstateret at det virker, så er det nok en god idé at have en fast tabsmeldingssag, som evt. udskiftes en gang om året (man kan sagtens lægge flere omgange revision ind på den samme sag, man skal bare omdøbe foregående revisionsfaneblad i sagen til "1. revision", "2. revision" etc.)

**Comment by kbevers** [comment]
Intet nyt i månedsvis og der er tabtmeldt en del punkter i mellemtiden. Jeg vurderer at der ikke er en fejl i koden og lukker dette issue. 

Se https://kortforsyningen.github.io/FIRE/tips/tabsmelding.html for en vejledning i hvordan punkter tabsmeldes.
