### ISSUE TITLE
Installation af fire 1.2.1 lykkedes ikke

### ISSUE THREAD

**Issue by mrlarshole** [Kortforsyningen/FIRE#469]
(base) C:\>activate fire

(fire) C:\>cd fire/fire

(fire) C:\fire\FIRE>git fetch origin
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 122 (delta 69), reused 89 (delta 46), pack-reused 0
Receiving objects: 100% (122/122), 6.42 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (69/69), completed with 16 local objects.
From https://github.com/kortforsyningen/FIRE
   a8c80a7..0f8692b  1.2                 -> origin/1.2
 * [new branch]      backport-465-to-1.2 -> origin/backport-465-to-1.2
 + e4afe09...cba29e3 gh-pages            -> origin/gh-pages  (forced update)
   9c09ca9..24aa377  master              -> origin/master
 * [new tag]         1.2.1               -> 1.2.1
 * [new tag]         fire-1.2.1          -> fire-1.2.1

(fire) C:\fire\FIRE>git checkout fire-1.2.1
Previous HEAD position was 9c09ca9 Udsted advarsel hvis niv-regneark skabt med en tidligere version bruges
HEAD is now at 0f8692b Korriger beregningsvejledning

(fire) C:\fire\FIRE>fire --version
fire, version 1.2.0

**Comment by kbevers** [comment]
Ups. Prøv lige igen, jeg havde glemt en lille ting

**Comment by mrlarshole** [comment]
(fire) C:\fire\FIRE>
(fire) C:\fire\FIRE>git fetch origin
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 38 (delta 19), reused 38 (delta 19), pack-reused 0
Unpacking objects: 100% (38/38), 115.05 KiB | 381.00 KiB/s, done.
From https://github.com/kortforsyningen/FIRE
   0f8692b..031c063  1.2        -> origin/1.2
 + cba29e3...9511fe4 gh-pages   -> origin/gh-pages  (forced update)

(fire) C:\fire\FIRE>git checkout fire-1.2.1
HEAD is now at 0f8692b Korriger beregningsvejledning

(fire) C:\fire\FIRE>fire --version
fire, version 1.2.0

**Comment by kbevers** [comment]
Prøv lige med `git checkout 031c063`

**Comment by mrlarshole** [comment]
Så var den der, tak.

(fire) C:\fire\FIRE>git checkout 031c063
Previous HEAD position was 0f8692b Korriger beregningsvejledning
HEAD is now at 031c063 Opdater versionsnummer til 1.2.1

(fire) C:\fire\FIRE>fire --version
fire, version 1.2.1
