### ISSUE TITLE
Oprettelse af permanente GNSS-stationer

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#471]
En del permanente GNSS-stationer er ikke oprettet i databasen. En ufuldstændig liste:

* `ESH5`
* `TA01`-`TA11`

En del af forklaringen på at de ikke er oprettet er, at vi ikke har en klar vejledning i hvordan det skal gøres. Det bør kunne klares som en revisionsøvelse men det ligger ikke fast hvilke punktinfo der skal knyttes til stationerne. Her kan man nok med fordel søge inspiration i de eksisterende stationers data.

**Comment by kbevers** [comment]
TAPAS stationerne er registrerede med landsnumre:

```
  K-63-05437	 TA01
 96-07-00807	 TA02
103-03-00818	 TA03
 96-04-00809	 TA04
103-12-00004	 TA05
102-03-00810	 TA06
101-02-00008	 TA07
102-09-01080	 TA08
103-05-00806	 TA09
103-04-00815	 TA10
 98-07-00805	 TA11
```

Dvs der skal kun tilføjes et `IDENT:GNSS` til hver af dem.

**Comment by kbevers** [comment]
TAPAS stationerne er nu lagt i FIRE. Koordinat til ESH5 udestår.

**Comment by xidus** [comment]
ESH5 er dd. lagt i databasen (PROD+TEST).
