### ISSUE TITLE
niv udtræk-revision: Tilføj buffer til polygonsøgning ved udtræk af opmålingsdistrikter

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#473]
Det hænder at enkelte punkter ikke udtrækkes fordi de ligger lige uden for opmålingsdistriktets polygon. En 25m buffer i søgningen burde kunne løse det problem.

**Comment by Palle-N** [comment]
Den er vigtig, har netop igen problemet i Ikast-Brande Kommune hvor vi ved kontrol af teksterne konstaterer at vi ikke har været ved 2 punkter fordi de ikke var med på arbejdskortet. De digitaliserede sognegrænser passer ikke altid helt med forholdene i marken, derfor foreslår jeg en buffer på 50 meter i stedet for.
Tit ser vi en sognegrænse skal følge en å eller bæk, men den digitaliserede grænse kan godt ligge 10 meter eller mere parallelt ved siden af.

**Comment by kbevers** [comment]
Okay, jeg ser om jeg kan få den løst hurtigt. Det burde ikke være så kompliceret. Satser på den kommer med i version 1.3 cirka 1. december.

**Comment by kbevers** [comment]
@Palle-N Kan du komme med et eksempel? Du har lavet et udtræk i Ikast, hvilke opmålingsdistrikter er det helt præcist? Og hvilke 2 punkter er det du har misset i udtrækket?

**Comment by Palle-N** [comment]
De 2 punktnumre i Ikast-Brande Kommune er:

109-02 09140
109-02-09167

Punkterne er med i revisions filen, men ikke på arbejdskortet.
