### ISSUE TITLE
Tildeling af GI-numre fungerer ikke når der er mere end et GI-punkt i "nyoprettede" listen

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#485]
Det viser sig (se sag F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\5D_OPRETTELSE) at der kun udtrækkes et GI-nummer når nyetablerede punkter markeres som "GI".

Derfor har de fire nyoprettede 5D-punkter BRND, HARE, ROEB og VEJE alle fået GI-nummer 2403.

**Comment by kbevers** [comment]
Ja, den er tydeligvis blevet implementeret for naivt. Der skal bruges en strategi tilsvarende den i `FireDb.tilknyt_landsnumre`.

**Comment by xidus** [comment]
Den er på pause lige nu, men som aftalt lægger jeg seneste lokale rettelser op og laver et pull request, så det er muligt at arbejde videre med dét, jeg har.
