### ISSUE TITLE
Tilføjelse af kolonne med label nummer i ...-punkter.geojson fil

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#491]
Nuværende ...-punkter.geojson fil indeholder kolonnerne 

id    H      sH     delta     fastholdt

Til det efterfølgende arbejde i QGIS og dokumentation overfor kunder er det en fordel, hvis der også findes kolonnen lbnr, der er punktnummeret i landsnummeret eller hele identen ved G.I. punkter.

For eksempel med manglende lbnr se 
\\prod.sitad.dk\dfs\CU2314\F-DREV\GRF\Data\GEO\BC\Niv_Opgaver\2021\VEDL_RINGKOEBING_SKJERN_NORD\2021_RINGKØBING_SKJERN_NORD.qgs

for eksempel med lbnr se 
F:\GRF\Data\GEO\LM\Planlægning\Ressource 2021\DMI\DMI flyttet målere.qgs

**Comment by busstoptaktik** [comment]
Jeg synes også mest det ligner et visualiseringsspørgsmål, og dermed en ting der hører hjemme i QGIS-opsætningen. Men dermed jo også et spørgsmål om hvor/hvad/hvordan skabeloner til QGIS-arbejde skal gemmes/vedligeholdes/administreres: Det er vel ikke udelukket at de hører til her.

**Comment by kbevers** [comment]
> Det er vel ikke udelukket at de hører til her.

Det er meget muligt, evt. som en del af QGIS plugin når vi kaster os over det igen. Jeg ved at Erik pusler med at finde gode måder at visualisere de forskellige data på men det skal vist lige finde sin form før det for alvor giver mening at lave en samling af style filer.

**Comment by ErikLysdal** [comment]
Med kommandoen regexp_substr(id, '\\d+$') sorteres bogstaverne G.M. og G.I. bort så tilbageværende nummereringen henviser til forkert punkt og er ikke en brugbar kommando under kontrol af beregningen.
Kommandoen anvendes pt ved oprettelse af ekstra kolonne inden visuel aflevering af oversigt til kunde. Efter kommandoen foretages hver gang manuel kontrol og genindlæsning af geojson filen. Så omvej til at etablere kolonne med Lbnr er fundet og bliver gentaget inden alle afleveringer af oversigtsplot.

**Comment by kbevers** [comment]
Jeg er ikke sikker på jeg forstår opfølgningen her. @ErikLysdal har du fundet en vej eller skal vi forsøge at dumpe G.M./G.I.-numrene ned i geojsonfilen?
