### ISSUE TITLE
Forslag: Udvid eksisterende validering og reformatering af identer til at dække tilfælde fra refgeo-migrering.

### ISSUE THREAD

**Issue by xidus** [Kortforsyningen/FIRE#499]
Da jeg tilføjede tests til valideringsfunktionerne for identer i fire.ident var det nærliggende at tage udgangspunkt i [de tekststrenge][LINK_TIL_IDENT_PARSER], der var blevet matchet under migreringen fra refgeo til fire.

De fleste af disse kunne dog ikke klargøres med funktionaliteten i fire.

Spørgsmålet er i første omgang, om de (nogle eller alle) skal kunne understøttes eller ej.

[LINK_TIL_IDENT_PARSER]: https://github.com/Kortforsyningen/FIRE-DDL/blob/master/pre-migration/identer/parse_idents.py

**Comment by kbevers** [comment]
> Spørgsmålet er i første omgang, om de (nogle eller alle) skal kunne understøttes eller ej.

Først om fremmest, så er det nok nyttigt at vide at alt whitespace er strippet fra identer ved indlæsning i FIRE. Bortset fra mellemrum der adskiller en eventuel regionskode fra identen (fx `GL  ABCD`). Hvis det samme gøres for testmaterialet går det nok væsentligt bedre for testen men der vil muligvis stadig være nogle vi ikke finder med den nuværende fire-kode.

**Comment by kbevers** [comment]
Med #581 er den væsentligste validering vist på plads. Der vil være enkelte ældre identer som nok ikke behandles korrekt af vores nuværende kode men de vil meget sjældent, hvis overhovedet, vær i brug. Jeg lukker denne, men hvis det viser at være nødvendigt at gøre yderligere kan den altid åbnes igen.
