### ISSUE TITLE
Fejl ved ilæg-revision...

### ISSUE THREAD

**Issue by Palle-N** [Kortforsyningen/FIRE#509]
Projekt: F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\DMI_HORNBAEK

Jeg har oplevet nedenstående, som jeg ikke umiddelbart kan finde en fornuftig forklaring på.

Ifm. med indsættelse af en revisionsfil lægger den noget fejltekst ind på 4 punkter, ingen fejlmelding, helt tilfældigt jeg opdager det ved et stikkontrol af at det er gået godt. Det er kun 4 af punkterne det sker ved. Revisionsfilen som laver balladen hedder "2021_DMI_HORNBAEK_1-revision" og ligger i ovennævnte projekt.

```
  REGION:DK
  IDENT:refgeo_id             126156
  IDENT:landsnr               12-05-09064
  ATTR:beskrivelse            Sauntevej 63._x000D_
                              Hornbæk By.
                              Hus._x000D_
                              Punkt i SØ. gavl._x000D_
                              0.42 m fra S. hjørne._x000D_
                              0.08 m over sokkelkant._x000D_
  ATTR:bemærkning             Rev. uge 46 2021 PN.
```

Efterfølgende trækker jeg ud til revision igen, indsætter den en gang til, det er "2021_DMI_HORNBAEK_4-revision" jeg bruger, og fejlteksten forsvinder.

Jeg ser umiddelbart ingen fejl i "2021_DMI_HORNBAEK_1-revision" som er den der laver balladen.

```
  IDENT:landsnr               12-05-09064
-ATTR:beskrivelse            Sauntevej 63._x000D_
                              Hornbæk By.
                              Hus._x000D_
                              Punkt i SØ. gavl._x000D_
                              0.42 m fra S. hjørne._x000D_
                              0.08 m over sokkelkant._x000D_
  ATTR:bemærkning             Rev. uge 46 2021 PN.
  ATTR:beskrivelse            Sauntevej 63.
                              Hornbæk By.
                              Hus.
                              Punkt i SØ. gavl.
                              0.42 m fra S. hjørne.
                              0.08 m over sokkelkant.
```

**Comment by kbevers** [comment]
Det er et problem med linjeskift. Lidt forsimplet sagt er `_x000d_` en intern kode for "enter"-knappen, den burde egentligt blive sorteret fra allerede men der er nok en bizar situation der fremtvinger den. Vi må prøve at gøre lidt ekstra ud af at sikre den slags ikke kommer med i databasen.

**Comment by kbevers** [comment]
Løst i https://github.com/Kortforsyningen/FIRE/pull/566
