### ISSUE TITLE
Kan ikke lave udtræk til revision hvis der svares "Nej til opret-sag og ja til opret sagsark".

### ISSUE THREAD

**Issue by ReneTandsbjerg** [Kortforsyningen/FIRE#535]
```
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2022\VEDL_BILLUND_VEST>fire niv opret-sag VEDL_BILLUND_VEST "Vedligehold af højdefikspunktsnettet"
Sags/projekt-navn: VEDL_BILLUND_VEST  (8df47c77-32fa-4f9d-900a-cffd67475efa)
Sagsbehandler:     B012858
Beskrivelse:       Vedligehold af højdefikspunktsnettet
Opretter ny sag i prod-databasen - er du sikker?  (ja/NEJ):
nej
Opretter IKKE sag
Opret sagsregneark alligevel? (ja/NEJ):
ja
Skriver sagsregneark 'VEDL_BILLUND_VEST.xlsx'
Filen 'VEDL_BILLUND_VEST.xlsx' findes ikke.
Skriver: {'Nyetablerede punkter', 'Notater', 'Filoversigt', 'Sagsgang', 'Projektforside', 'Parametre'}
Til filen 'VEDL_BILLUND_VEST.xlsx'
Færdig! - åbner regneark for check.
---------------------------------------------------------------------------
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2022\VEDL_BILLUND_VEST>fire niv udtræk-revision VEDL_BILLUND_VEST 133-01 136-02 112-03 112-13
 Sag for VEDL_BILLUND_VEST er endnu ikke oprettet - brug fire niv opret-sag!
-------------------------------------------------------------------------------
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2022\VEDL_BILLUND_VEST>fire niv opret-sag VEDL_BILLUND_VEST "Vedligehold af højdefikspunktsnettet"
Filen 'VEDL_BILLUND_VEST.xlsx' eksisterer - sagen er allerede oprettet
---------------------------------------------------------------------------------------
```

**Comment by kbevers** [comment]
@ReneTandsbjerg hvad er brugsscenariet her? Som udgangspunkt laver man jo revisionsudtræk med henblik på at ændre noget, og for at det kan lade sig gøre er der brug for en sag. Så i det tiltænkte workflow giver det vist god mening at fejle her, men det kan være du har en alternativ anvendelse som vi ikke lige har overvejet oprindeligt?

**Comment by ReneTandsbjerg** [comment]
Jeg vil gerne lave et revisions udtræk på denne sag, hvordan gøres det så.? skal jeg starte helt forfra? 

hvorfor er der mulighed for at svare ja til at oprette sagsark, når der svares nej til at oprette en sag?

**Comment by kbevers** [comment]
> Jeg vil gerne lave et revisions udtræk på denne sag, hvordan gøres det så.? skal jeg starte helt forfra?

Ja, bare slet filerne der starter med `VEDL_BILLUND_VEST`. 

> hvorfor er der mulighed for at svare ja til at oprette sagsark, når der svares nej til at oprette en sag?

Fordi det gør det muligt at lave en beregning uden at lægge noget i databasen. Så fx kan du have et workflow i stil med:

```
> fire niv opret-sag REGN "her laver vi en sag UDEN at oprette den i databasen"
> fire niv udtræk-observationer REGN ...
> fire niv regn REGN
```
Bemærk at det her ikke er nødvendigt at lukke sagen, da det kun er oprettet lokalt sagsark og ikke en sag i databasen.

**Comment by ReneTandsbjerg** [comment]
Mange tak for svar. 
Go dag @kbevers
