### ISSUE TITLE
Vejledning i install

### ISSUE THREAD

**Issue by mrlarshole** [Kortforsyningen/FIRE#542]
I vejledingen til 1.3.0 på github, bør der stå at det er et condavindue som skal åbnes og ikke blot en commando-promt.
Der er et ”git clone” for meget i kommandoen:
git clone git clone https://github.com/Kortforsyningen/FIRE.git
Brugeren bør opdatere conda til ver 4.11.0 med flg. kommando:

conda update -n base -c defaults conda”

Vedr. 1.3.1  er dette godt eller skidtsvar efter at have kørt: git checkout fire-1.3.1
Previous HEAD position was 760a933 Merge pull request #516 from xidus/1.3
HEAD is now at 4fca6e3 Merge pull request #531 from Kortforsyningen/backport-530-to-1.3

**Comment by kbevers** [comment]
> I vejledingen til 1.3.0 på github, bør der stå at det er et condavindue som skal åbnes og ikke blot en commando-promt.

Det står der vel også?
![image](https://user-images.githubusercontent.com/13132571/149133403-1cc2f7b0-3bc6-4989-a3d9-d3fce974fff1.png)

Og så vidt jeg kan se er der også kun en enkelt runde `git clone`. Det må næsten være et andet sted du har kigget, så hvor er du stødt på de problemer? Jeg læser her https://kortforsyningen.github.io/FIRE/installation.html#fire 

> Vedr. 1.3.1 er dette godt eller skidtsvar efter at have kørt: 

Det er godt svar, men det er uforståeligt for det utrænede øje. Af samme grund bliver du senere i processen bedt om at tjekke versionen med `fire --version`. Det er nemmere at forstå.

**Comment by busstoptaktik** [comment]
@kbevers  sagde:
> Det må næsten være et andet sted du har kigget

Jeg tror det er teksten [her](https://github.com/Kortforsyningen/FIRE/releases) @mrlarshole refererer til

**Comment by kbevers** [comment]
Ja, det er det da nok. Det er også rodet at det står der frem for at henvise til eksisterende materiale.

**Comment by mrlarshole** [comment]
Joacims mail fra 9/12 2021 siger: FIRE 1.3.1 kan installeres på følgende måde, der forudsætter, at man har fulgt vejledningen til installation af FIRE 1.3.0, som kom i sidste uge:
https://github.com/Kortforsyningen/FIRE/releases/tag/fire-1.3.0

Det er her der er dobbeltkonfekt.

**Comment by mrlarshole** [comment]
Et hurtigt spørgsmål: 
Jeg kan skifte mellem test og prod database bare ved at skiftet teksten test til prod i den øverste linje inifilen:?
[general]
default_connection = test

**Comment by mrlarshole** [comment]
Undertrykker jeg .ini med --db options prod|test?

**Comment by kbevers** [comment]
@mrlarshole 

> Undertrykker jeg .ini med --db options prod|test?

Ja. Hvis du sætter `--db=test` fx så er du sikker på at du bruger testdatabasen. Hvis du ikke angiver noget så bruges det du har sat som `default_connection` i `fire.ini`.

**Comment by kbevers** [comment]
Jeg har rettet installationsvejledningen under release 1.3.0 til så de værste fejl og mangler er kommet i orden. Jeg tror fremadrettet vi bare skal henvise til websiden, så undgår vi nok lignende fejl.
