### ISSUE TITLE
Tabtgået punkter...

### ISSUE THREAD

**Issue by Palle-N** [Kortforsyningen/FIRE#543]
Hurtigt  spørgsmål, når vi tabsmelder et punkt, skal det stå med lille eller stort (Tabtgået/tabtgået)?
Tænker måske lille...

Vi har tidligere vendt at vi skal kunne genfinde et tabtgået punkt, tror også der er sket noget i sagen, jeg kan bare ikke finde noget om det nogen steder?

Jeg kunne tænke mig begge dele kort beskrevet i workshoppen under revision.

**Comment by kbevers** [comment]
> Tænker måske lille...

`ATTR:tabtgået`. En anden gang, hvis du er i tvivl, kan du spørge med `fire info infotype`:

```
>fire info infotype --db=prod ATTR
"ATTR" matcher følgende punktinfotyper:

ATTR:GI_punkt
ATTR:MV_punkt
ATTR:aerotriangulationspunkt
ATTR:bemærkning
ATTR:beskadiget
ATTR:beskrivelse
ATTR:ekstern
ATTR:fundamentalpunkt
ATTR:gnss_egnet
ATTR:hjælpepunkt
ATTR:højdefikspunkt
ATTR:muligt_datumstabil
ATTR:restricted
ATTR:sømærke
ATTR:tabtgået
ATTR:teknikpunkt
ATTR:tinglysningsnr
ATTR:vandstandsmåler
```

> Vi har tidligere vendt at vi skal kunne genfinde et tabtgået punkt, tror også der er sket noget i sagen, jeg kan bare ikke finde noget om det nogen steder?

Jeg kan ikke lige huske hvor vi endte med den. Jeg vender lige tilbage til den på et senere tidspunkt.

**Comment by Palle-N** [comment]
Det er modtaget... og noteret.
Afventer mht. sidste spørgsmål.

**Comment by kbevers** [comment]
Jeg kan se at det indtil videre er blevet ved snakken mht de tabtgåede punkter. De bliver sorteret fra når der laves revisionsudtræk. I er sikre på at I gerne vil have dem med ud fremadrettet?

**Comment by Palle-N** [comment]
Årh, så har vi talt/skrevet forbi hinanden.
Vi skal ikke ha´ de tabtgået med i revisionsudtræk.
Det sker nogle gange om året at vi finder et punkt i marken som umiddelbart ikke er registreret som valid, og typisk er det blevet meldt tabt, enten fordi at man ikke har kunne finde det ud fra teksten i beskrivelsen, eller at man har noteret et forkert punktnummer i den liste der skulle opdateres med tabtgået punkter, så er et forkert punkt meldt tabt, og det der reelt er tabtgået står stadigvæk som valid...
Den sidstnævnte fejl er vi ovre efter overgang til FIRE, her skal ikke fremstilles en særskilt liste med tabtgået punkter til opdatering, men blot noteres det er tabtgået i regnearket.
Så... det jeg efterlyser er muligheden for at gøre et tabtgået punkt valid igen, når vi nu lidt tilfældigt falder over dem i marken.

**Comment by kbevers** [comment]
Okay, ja, så misforstod jeg. Så tror jeg du kan gøre med et workflow i stil med nedenstående:

```
fire niv opret-sag SAG
fire niv udtræk-revision SAG K-01-23456
```
Sæt kryds i sluk ud for `ATTR:tabtgået`. Gem og luk regnetarket.
```
fire niv ilæg-revision SAG
fire niv luk-sag SAG
```

Når du sætter x i sluk-kolonnen så fjerner du den attribut.

**Comment by Palle-N** [comment]
Det vil jeg prøve næste gang.
Kan vi få det beskrevet kort i workshoppen under revision?

**Comment by kbevers** [comment]
> Kan vi få det beskrevet kort i workshoppen under revision?

Ja. Eller et andet sted i dokumentationen. Jeg vil på et tidspunkt gerne lave en sektion med små tips og tricks, jeg synes det hører bedre til der.

**Comment by kbevers** [comment]
> Kan vi få det beskrevet kort i workshoppen under revision?

Se https://kortforsyningen.github.io/FIRE/tips/tabsmelding.html
