### ISSUE TITLE
Fjern konfigurationstabel

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE#545]
Vi har i DDL'en en konfigurationstabel

https://github.com/Kortforsyningen/FIRE/blob/1d2c65bf890391ebd0bff4bf41689e88f4d89704/sql/ddl.sql#L115-L121

som primært er indført for at kunne holde styr på den absolutte placering af skitserne som de blev registreret med  fx `SKITSE:png_sti`. Med indførsel af Grafik-tabellen i #538 er dette ikke længere nødvendigt at konfigurationstabellen bør enten bruges på anden vis eller fjernes. Ligeledes for den tilsvarende SQLAlchemy klasse.

**Comment by busstoptaktik** [comment]
... hvilket fører mig til en digression om hvorvidt vi på langt sigt skal overveje at udfase SQLAlchemy helt: Der dukker ren rå SQL op i kodebasen flere og flere steder, så måske bør vi ind imellem overveje i hvor høj grad vi har brug for objekter-fra-tabeller: Hvor stor nytteværdi har vi reelt af at mappe-til-objekter, hvis vi alligevel har lettere ved at finde de rette data ved at sætte parametre i rå SQL-skabeloner (som man jo sagtens kan have et bibliotek af til faste delopgaver).

Provokerende tanke, men måske værd at overveje...

**Comment by kbevers** [comment]
Du skal prøve at slå SQLAlchemys SQL-log til engang ved lejlighed. Det giver et meget godt indblik i hvorfor det er rart at have :-) Det er klart at vi i visse situationer kan fintune queries bedre ved at gå udenom SQLAlchemy men jeg tror det bliver rigtig rodet hvis det er den eneste vej vi går. Med det sagt, så er der ikke verdens bedste match mellem vores loosey-goosey datamodel og den slags database SQLAlchemy nok typisk anvendes på, og dermed primært er designet til at arbejde op mod.

**Comment by busstoptaktik** [comment]
Jeg er ikke i tvivl om at datamodellen passer skidt ind i SQLAlchemys univers, men det er ikke fordi modellen er loosey-goosey, det er fordi den relationelle mafia tvang os til at mappe et (fundamentalt) dokumentbaseret problemdomæne ind i en relationel verden.

Det kan vi ikke gøre ret meget ved lige nu, men der kommer en dag, hvor vi reimplementerer, øger robusthed og vedligeholdelighed ved løsere systemkomponentkobling, og brug af databasen som det, den er allerbedst til: Som integrationsplatform.

Forhåbentlig er vi så også gået over til PostgreSQL og eller PostGIS i mellemtiden, men selv Oracle understøtter hybride dokumentrelationelle tilgange i dag, så vi kan mix-og-matche dokument-og-relationelle søgninger alle vegne hen.

**Comment by kbevers** [comment]
Det er vist en discussion der er langt uden for scope for det her isssue

**Comment by busstoptaktik** [comment]
Det var det jeg forsøgte at indikere med formuleringen "det kan vi ikke gøre ret meget ved nu".
