### ISSUE TITLE
ilæg_observationer tager ikke højde for slukkede observationer

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#548]
Version 1.3.1
Observationer der i Projekt excel arket under fanebladet "Observationer" er markeret med x i Sluk kolonnen bliver alligevel overført til DB med kommandoen "fire niv ilæg-observationer projektnavn".
Observationer der slukkes for skyldes de er fejlbehæftede og heller ikke medtages i beregningen. Primært er fejlbehæftede observationer udkommenteret inden indlæsningen, men enkelte kan glippe og udkommenteres i excel arket.

**Comment by kbevers** [comment]
Når jeg læser dokumentation og kode ser det ud til at det aldrig har været hensigten at sluk-markerede observationer skulle udelades ved databaseilægning. Altså, det har kun været tænkt som en funktion i forhold til beregning men hvis det er praktisk også at bruge den markering til at springe observationer over ved ilægning tror jeg ikke der er noget i vejen for det. Ser du nogen udfordringer ved det @busstoptaktik?

**Comment by busstoptaktik** [comment]
Tanken bag arbejdsgangen er at *kontrolberegningen er en del af kvalitetskontrollen*, og at man derfor under kontrolberegningsiterationer kan tænde og slukke for enkeltobservationer *som man har mistanke til*.

Når man har fået bekræftet sine mistanker er det meningen at man udkommenterer i observationsfilen, så fejlen bliver rettet ved kilden (som bliver gemt separat), og indlæser observationer igen.

Det var tanken bag. Hvis det er noget knold kan vi jo bare lave det om, men det betyder at de gemte observationsfiler kommer til at have dårligere kvalitet

**Comment by kbevers** [comment]
@ErikLysdal hvad siger du her, er det noget knold så vi skal lave det om eller giver det mere mening efter Thomas' uddybning af rationalet bag den nuværende implementering?

**Comment by ErikLysdal** [comment]
Er tanken den traditionelle, at de valgte observationer skal gemmes i både observationsfilerne og FIRE - så fortsætter vi med at gentage indlæs - kontrolberegning - indlæs - kontrolberegning etc.
Min forventning var, at godkendte observationer og beregninger udelukkende skal findes i FIRE. Det vil reducere antallet af indlæsninger til én gang, hvorefter der regnes videre med Excel arket og godkendte observationer gemmes i FIRE. Skal observationer efterfølgende anvendes vil det kunne ske med udtræk fra FIRE og ikke med anvendelse af observationsfilen.
Min forventning var åbenbart forkert - så vi arbejder videre med adskillige indlæsninger af observationsfilen.

**Comment by kbevers** [comment]
Vi ændrer det så "sluk" betyder at en observation ikke lægges i databasen. Det bør desuden allerede være muligt at redigere de indlæste observationer direkte i regnearket. De to ting til sammen bør kunne forsimple arbejdsgangen gevaldigt, sådan at observationsfilerne kun indlæses i regnearket en gang, hvorefter alle nødvendige ændringer foretages der.
