### ISSUE TITLE
Manglende udstilling af ny-etablerede punkter med kote

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#557]
Nyetablerede punkter udstilles ikke i Valdemar efter tildelingen af kote.
Nu ved jeg selvfølgelig ikke, hvornår det er tænkt, at nyetablerede punkter skal udstilles i Valdemar applikationen. Umiddelbart har jeg forestillet mig, at punkter udstilles efter de er tildelt en kote i FIRE, men der er sikkert lavet nogle større tanker omkring det.
Det eneste jeg ydmygt kan konstatere er, at efter kørslen "fire niv ilæg-nye-koter PROJEKTNAVN" får højdefikspunkterne tildelt en kote i FIRE, men ikke bliver udstillet i Valdemar.
Eksempel med manglende udstilling i Valdemar kan ses med bl.a. punkt K-75-9420.
Projektet ligger her: F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\DMI_ESBJERG
og er forsøgt overført til FIRE d 14 januar 2022.

**Comment by kbevers** [comment]
Det ser besynderligt ud. Det undersøges sammen med DAT.

**Comment by kbevers** [comment]
Problemet er løst af DAT
