### ISSUE TITLE
Skal 'beskrivelse' altid udfyldes ved `fire niv ilæg-nye-punkter`?

### ISSUE THREAD

**Issue by Palle-N** [Kortforsyningen/FIRE#561]
Jeg har lige oplevet at jeg ikke kunne ilæg-nye-punkter uden jeg skulle skrive et eller andet i kolonne F, "beskrivelse".

I langt de fleste tilfælde skriver jeg teksten ind, men det sker at vi skal bruge et nyt punktnummer her og nu. Jeg har ikke tidligere skulle skrive i "beskrivelse" kolonnen for at køre ilæg-nye-punkter. 

Er der en fejl, eller er det meningen at vi skal notere noget i feltet nu?

**Comment by kbevers** [comment]
Jeg har brug for en fejlmeddelelse og sagsfilerne for at kunne dykke ned i det her. Umiddelbart ser det ud som i koden at det burde være muligt at oprette et punkt uden beskrivelse, men jeg vil opfordre til altid at gøre det alligevel. Selv en lille kort beskrivelse er bedre end ingenting.

Husk også at det der står i beskrivelsen ryger ud på Valdemar.

**Comment by Palle-N** [comment]
Jeg prøver igen ved det næste nye punkt vi etablerer.

Det sker kun sjældent at vi ikke er i stand til at indsætte en korrekt tekst når vi har brug for et nyt punktnummer, og når det sker opdateres teksten inden for få dage.

**Comment by kbevers** [comment]
> og når det sker opdateres teksten inden for få dage.

Okay, så synes jeg vi skal gøre det til et krav at sætte en beskrivelse ind. I de tilfælde hvor den fulde tekst ikke kan skrives ind med det samme kan I skrive en mindre detaljeret tekst som revideres senere.
