### ISSUE TITLE
Manglende punkter i Ringkøbing - Skjern kommune

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#562]
Nyetablerede punkter fra vedligeholdelsesopgaven i Ringkøbing - Skjern kommune vises ikke i Valdemar, men optræder i FIRE.
Sti for vedligeholdelsesopgaven i 2021 er F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\VEDL_RINGKOEBING_SKJERN_NORD
Nye punkter ses ikke, selvom de er med i FIRE f.eks 118-08-9077, -9082, -9087 
Derudover er det et ældre punkt 118-08-00806 som heller ikke optræder i Valdemar.

**Comment by kbevers** [comment]
DAT konstaterede tidligere i dag problemer med nogle punkter der ikke var blevet udstillet som forventet. Så vidt jeg kan se er dem du nævner her blandt de punkter. En delvis løsning er allerede fundet men det kunne se ud som om at der stadig er noget der driller. Jeg har givet DAT besked.

**Comment by kbevers** [comment]
Ved nærmere eftersyn ser det ud til at punkterne er tilgængelige i Valdemar men af eller anden grund dukker de ikke op i søgninger. Work-around indtil videre er at gå direkte til dem vha link:

`https://valdemar.kortforsyningen.dk/FikspunktFrontend/fikspunktdetails.php?type=Hoejdefikspunkt&region=dk&udRefSys=25832&koteSys=DVR90&number=<landsnummer>`, hvor `<landsnummer>` erstattes med det fuldtudskrev landsnummer (dvs. 118-08-09077 og ikke 118-08-9077).

Eksempelvis: [https://valdemar.kortforsyningen.dk/FikspunktFrontend/fikspunktdetails.php?type=Hoejdefikspunkt&region=dk&udRefSys=25832&koteSys=DVR90&number=118-08-09082](https://valdemar.kortforsyningen.dk/FikspunktFrontend/fikspunktdetails.php?type=Hoejdefikspunkt&region=dk&udRefSys=25832&koteSys=DVR90&number=118-08-09082)

**Comment by kbevers** [comment]
Punkterne kan ikke søges frem i Valdemar fordi de i overførslen til Geobanken får sat en forkert MV_STATUS (planfikspunkt fremfor højdefikspunkt). Det sker fordi `ATTR:højdefikspunkt` ikke er sat på punkterne. Præcis hvad årsagen til det er på nuværende tidspunkt uklart for mig, men det kan https://github.com/Kortforsyningen/FIRE/issues/563 der omhandler registrering af afmærkningstypen.

Indtil videre vil jeg bede om at der under "afmærkning" ved oprettelse af nye punkter altid skrives "Bolt" fremfor variationer af "AFM:2700", hvilket det tyder på sker i nogle tilfælde. Tilsvarende med "Lodret bolt" og "AFM:2701" samt "Skruepløk" og "AFM:2950". Det tager i hvert fald hånd om noget af problemet (korrekt punktbeskrivelse på Valdemar).

**Comment by kbevers** [comment]
Punkterne er nu at finde på Valdemar
