### ISSUE TITLE
udtræk-revision med eller uden 0 i løbenummeret

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#567]
Ved kommandoen "fire niv udtræk-revision PROJEKTNAVN punktID" skal hele løbenummeret angives.
Nedenfor er eksempel hvor 120-02-9104 ønskes udtrukket, men bliver ikke fundet i databasen.
Angives punktnummeret i stedet med 120-02-09104 udtrækkes punktet.

Problemet har lav prioritet, da jeg nu er klar over problemet, men den manglende fleksibilitet strider mod de andre FIRE kommandoer, hvor 0 foran løbenummeret ikke behøver angivet.

Eksempel:
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\NIVEAU_KDI_VESTKYST>fire niv udtræk-revision NIVEAU_KDI_VESTKYST 120-02-9104 120-06-9007 120-03-804 120-09-9008 134-09-9026 134-09-9013 134-09-9034 134-09-9032 118-04-9073
FEJL: Ident 120-02-9104 ikke fundet i databasen

(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\NIVEAU_KDI_VESTKYST>fire info punkt 120-02-9104

--------------------------------------------------------------------------------
 PUNKT 120-02-09104
--------------------------------------------------------------------------------
  Lokation                    POINT (8.50484308280512 55.9032954085247)
  Oprettelsesdato             1999-05-06 10:36:00
  AFM:2701                    Lodret bolt.

**Comment by kbevers** [comment]
Det er noget rod at der ikke er samme opførsel på tværs af programmerne. Umiddelbart burde det være et easy fix med et kald til `fire.ident.klargør_identer_til_søgning()` cirka her:

https://github.com/Kortforsyningen/FIRE/blob/d2fdd34cd064c068dfb12b91e4aa5d8eba1b4e1c/fire/cli/niv/_udtr%C3%A6k_revision.py#L81-L85
