### ISSUE TITLE
geo_ref.sglite

### ISSUE THREAD

**Issue by Palle-N** [Kortforsyningen/FIRE#569]
Henrik har i mange år serviceret os med opdaterede udtræk fra db i filen geo_ref.sqlite.

Den fil bruger vi i flere af vores programmer i marken, den seneste udgave er fra 18.12.2020

Hvordan håndterer vi det i fremtiden, sådan at vi har opdateret materiale med i marken, er det muligt at fremstille en tilsvarende fil i FIRE?

seneste udgave ligger her: F:\GRF\Data\GEO\LM\Fixopl2020

**Comment by kbevers** [comment]
Se https://github.com/Kortforsyningen/FIRE/issues/474. Jeg har tidligere aftalt med @ErikLysdal at vi for nuværende ikke gør noget, da de næste to målesæsoner er i områder hvor der ikke er væsentlige ændringer i FIRE i forhold til REFGEO. Det er desværre langt fra trivielt at lave en direkte erstatning af `geo_ref.sqlite`, så der er ikke en løsning lige rundt om hjørnet. Det vil nok være god ide at få på arbejdsprogrammet næste år.

**Comment by Palle-N** [comment]
Okay, det vil jeg give ham ret i, men præcis i dag havde det været en hjælp, vi arbejder lige nu i en del af Ringkøbing-Skjern Kommune, hvor der i 2021 blev foretaget punktrevision.
Her har René konstateret et punkt tabtgået, og erstattet det med et nyt. Det kan vi ikke se, så Jacob konstaterer samme punkt tabtgået, og gør klar til at etablere et nyt punkt, heldigvis samme sted som René valgte sidste år, så det gik godt denne gang.

**Comment by kbevers** [comment]
Jeg medgiver at det ikke er perfekt og håber der ikke opstår alt for mange af den slags situationer indtil der er fundet en ordentlig løsning!
