### ISSUE TITLE
Udstilling af tabtgået punkt i Valdemar

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#589]
Når der i Valdemar ønskes et overblik over eksisterende højdefikspunkter indenfor et kortudsnit vises enkelte punkter, som et eksisterende højdefikspunkt selvom punktet er angivet med afmærkninsgbeskrivelsen Tabtgået. Punktet bør kun vises, hvis søgekriteriet Tabtgået er valgt.
![billede](https://user-images.githubusercontent.com/78030283/155306279-fd3bf047-d046-4e6f-802e-be8b0b00ba67.png)

I filen F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\NIVEAU_KDI_VESTKYST\NIVEAU_KDI_VESTKYST-revision1.xlsx
er flere punkter meldt tabtgået f.eks. 118-04-09073

Revisionfil for 118-04-09073 angiver følgende attributter:
LOKATION
ATTR:muligt_datumstabil
ATTR:beskrivelse
AFM:vertikal
AFM:højde_over_terræn
AFM:2700
ATTR:højdefikspunkt
ATTR:bemærkning
ATTR:tabtgået

Tilsvarende problem med visningen i Valdemar er ikke gældende i andre projekter f.eks
F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\VEDL_SILKEBORG_NORD\2021_VEDL_SILKEBORG_NORD-revision.xlsx
hvor bl.a. 106-02-09033 vises korrekt. Begge punkter har attributten ATTR:tabtgået

**Comment by kbevers** [comment]
Det ser ud til at være et problem i overførslen til Geobanken. [Issue](http://sdfe-git/fikspunktregister/fire2fiks/-/issues/31) oprettet hos DAD.

**Comment by kbevers** [comment]
Problemet bundet i at der er nogle bagvedliggende tabeller der ikke er blevet opdateret. De er nu manuelt opdateret og muligheden for at gøre det automatisk afsøges. De tabtgåede punkter på vestkysten fremtræder nu helt tabtgået på Valdemar (kommer kun frem i søgning når tabtgået efterspørges).

**Comment by kbevers** [comment]
Fejlrettelse i overførsel til geobanken er nu rullet ud
