### ISSUE TITLE
Helt projekt udstilles ikke

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#598]
Projektet F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\HAVN_SKAGEN blev opdateret i FIRE d 8. marts 2022, men opdaterede koter og nye punkter udstilles endnu ikke.
Opdaterede koter og nye punkter med korrekt ATTR:højdefikspunkt attribut findes i FIRE.

**Comment by kbevers** [comment]
Så vidt jeg kan se *er* koter på eksisterende punkter blevet opdateret. Bemærk at Valdemar fornyligt er blevet ændret så der altid vises tre decimaler på koter. Det er gjort for at undgå situationer hvor vi udstiller koter med 15 decimaler. K-48-09014 har koten 1,44877 som afrundes til 1,449. Den gamle kote var 1,44888 hvilket også afrundes til 1,449. Tilgår man data via Datafordelerens API får man alle decimalerne med.

Jeg kan se at de nye punkter har fået en ATTR:højde_over_terræn = 0. Det ser ud til at være synderen. Der er klart en fejl i `fire ilæg-nye-punkter`, der gør at data ikke indsættes korrekt. Det virker usædvanligt for mig at højden over terræn er 0 men måske den er god nok?

**Comment by kbevers** [comment]
>  K-48-00914 har koten 1,44877 som afrundes til 1,449. Den gamle kote var 1,44888 hvilket også afrundes til 1,449. Tilgår man data via Datafordelerens API får man alle decimalerne med.

Det her er noget sludder. Den nye kote er 1,44888 og den gamle 1,44877. Vi udstiller den gamle. Det skal vi naturligvis ikke. Jeg tager fat i DAT i morgen og prøver at finde ud af hvad der er gået galt.

**Comment by kbevers** [comment]
> Der er klart en fejl i fire ilæg-nye-punkter, der gør at data ikke indsættes korrekt. 

Data indsættes korrekt, men vises forkert med `fire info punkt`. Problemet er rettet i #599. 

Og med det konkluderer jeg endegyldigt at problemet ligger i overførslen til geodatabanken. DAT er blevet gjort opmærksom på fejlen, men en løsning er så vidt jeg ved ikke fundet endnu.

**Comment by kbevers** [comment]
Det forlyder at data nu er ført videre til Databanken og dermed også er tilgængelig på Valdemar. Jeg har lavet stikprøvekontorl på en håndfuld punkter og de har alle de nye koter.
