### ISSUE TITLE
FIRE grafik - skitse redigering

### ISSUE THREAD

**Issue by jsnSDFE** [Kortforsyningen/FIRE#604]
Ift. bl.a. punktrevision får vi sommetider behov for at redigere en skitse. Kan man hente .png filen og arbejde med den lokalt? 
Når jeg bruger "fire grafik vis", åbnes skitsefilen i "Photos" appen. Jeg får ikke lov til at gemme eller redigere filen.

**Comment by kbevers** [comment]
I det øvre højre hjørne er der en menu (de tre prikker). Her kan du vælge gem som: 

![image](https://user-images.githubusercontent.com/13132571/159432961-1b28cb13-f0d7-4068-9e71-b4d97be0792a.png)

Med hensyn til skitserne er der to ting at være opmærksom på:

1. Rettelser i skitser bør ske i de oprindelige filer, eksportes til png og så lægges i databasen
2. Mekanisme til opdatering af skitserne i Valdemar udestår. Jeg nåede ikke at få den del på plads i januar da jeg tog hånd om skitserne på vores udviklingssprint. Jeg har efterfølgende prioriteret det ned da det var mit indtryk at der var langt i mellem skitserevideringer. Jeg flytter det højere op på listen, da det lader til at der nu er et behov for det og det vil være rart at få ud af verden

**Comment by jsnSDFE** [comment]
Når jeg vælger "gem som", får jeg lov at vælge destination som normalt, men efter at jeg vælger "gem", kommer denne meddelelse frem:
![Udklip](https://user-images.githubusercontent.com/78353543/159895047-6f3140f4-7b44-4158-8519-6e6732371e17.PNG)
Appen gemmer en .png lokalt, men den er tom. Kan det have noget at gøre med appen?
