### ISSUE TITLE
"ilæg-revision" - rettelse af lokationskoordinater

### ISSUE THREAD

**Issue by jsnSDFE** [Kortforsyningen/FIRE#606]
Ved "ilæg-revision" har jeg noteret at at FIRE vil "rette" 154 lokationskoordinater. Men jeg har reelt kun rettet 12. 
I kolonne F findes der godt nok 154 lokationskoordinater, men 142 af disse står der kun da de ikke er besøgt. Disse er desuden ikke ændret, og "x" i kolonne H er ikke fjernet ved de gældende punkter.
Det undre mig at FIRE vil "rette" lokationskoordinater på punkter som ikke er besøgt. Kan det være rigtigt?

![Lokationskoordinater](https://user-images.githubusercontent.com/78353543/161788417-87c675ef-588c-44fd-83fe-e0e4d4351a99.PNG)

![Lokationskoordinater2](https://user-images.githubusercontent.com/78353543/161788462-277a1602-8978-4fdc-898e-02aa394a6ab2.jpg)

[2022_VEDL_KERTEMINDE_NORD-revision.xlsx](https://github.com/Kortforsyningen/FIRE/files/8419537/2022_VEDL_KERTEMINDE_NORD-revision.xlsx)

**Comment by kbevers** [comment]
> Det undre mig at FIRE vil "rette" lokationskoordinater på punkter som ikke er besøgt. Kan det være rigtigt?

Ja, men jeg kan godt forstå hvorfor det ser mærkeligt ud. Krydserne i "ikke besøgt" kolonnen bliver ikke læst af `fire niv ilæg-revision`, de er der udelukkende for at hjælpe jer med at holde styr på hvilke punkter I har været forbi. Så når der står noget i "ny værdi" regner programmet med at det er noget nyt der skal indsættes. Medmindre feltet "id" er udfyldt, så ved programmet godt at det er noget der kommer fra databasen. Det vil altså sige at når I kopier indholdet fra "tekstværdi" og "talværdi" ukritisk over i "ny værdi", så vil det her ske. Det er åbenlyst uhensigtsmæssigt så det skal vi have lavet om på. 

Løsningen nu og her er, at fjerne lokationskoordinaterne fra "ny værdi" de steder hvor der er x i "ikke besøgt".

Den langtidsholdbare løsning er at få `fire niv udtræk-revision` til at udfylde "id"-felterne for lokationskoordinaterne. @xidus vil du tage dig af det?

**Comment by xidus** [comment]
Jeg ser på det.
